### ISSUE TITLE
Let developers receive money from plug-ins 

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1007]
**Is your feature request related to a problem? Please describe.**
Developers currently are not motivated to.build plug-ins because they can't receive money for them. 

**Describe the solution you'd like**
You need to come up with the right incentive structure that suits both the company and developers and allows them to receive MOney from building plug-ins.

Options: 
- let users pay for plug-ins (I think they will need to.pay from web cuz of appstore rules, like obdisian) and send those money to devs. Check obsidian
- pay to devs based on plug-ins usage. For example, smth like $0.1 for each install

**Describe alternatives you've considered**
Check how obsidian does it. It would also be great to do a mini research and show how other apps with internal marketplaces solve these issues

**Comment by josancamon19** [comment]
Isnt Ayush doing this?

**Comment by beastoin** [comment]
who is Ayush?

**Comment by beastoin** [comment]
how does it work bro @josancamon19 ? really excited to see this part of our product launch!!!

**Comment by beastoin** [comment]
@kodjima33 bruh, our great stakeholder, is it good enough to close this ticket ?
