### ISSUE TITLE
Ability to Stream raw audio ($500)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1009]
**Is your feature request related to a problem? Please describe.**
Lots of developers want to receive raw audio from the device, real-time. 

**Describe the solution you'd like**
A websocket that streams raw audio. Basically in the app add another field below webhooks

This might be too expensive for our side in terms of battery, but i believbe we can't limit developers with such basic features

**Comment by AnkushMalaker** [comment]
I can do this, but what do you mean by "this might be too expensive for our side in terms of battery"?
Does the Friend not stream all the time?

**Comment by beastoin** [comment]
@faraza yoooooou, $500 is so sweet bro ?

**Comment by josancamon19** [comment]
will get this done tmrw, will be done from back, prioritized to help @faraza on his usecase.

@faraza does 3/5 secs chunk work? a ws seems overload complexity in our + your side at this point. lmk

**Comment by josancamon19** [comment]
If succesful and ppl want to use it as a plugin, we'll build the plugin infra.

**Comment by josancamon19** [comment]
Done
```python
    async def send_audio_bytes_developer_webhook(data: bytearray):
        webhook_url = get_user_webhook_db(uid, WebhookType.audio_bytes)
        if not webhook_url:
            print('No developer webhook url')
            return
        webhook_url += f'sample_rate={sample_rate}'
        try:
            response = requests.post(webhook_url, data=data, headers={'Content-Type': 'application/octet-stream'})
            print('Developer webhook response', response.status_code)
        except Exception as e:
            print(f"Error sending audio bytes to developer webhook: {e}")

```

This is the request that will be made.

Let's test it, and polish it, and then we'll add it to docs.

**Comment by beastoin** [comment]
Does it works for you bro @josancamon19  ? if yes, just close the ticket 😌

**Comment by AnkushMalaker** [comment]
Which PR is this in? I could help test it

**Comment by beastoin** [comment]
great @AnkushMalaker ! It's ready on the latest app version pls check  https://discord.com/channels/1192313062041067520/1296607070661116026/1296607070661116026
