### ISSUE TITLE
Sometimes text is cut in the transcription. If I say, 1,2,3,4,5,6,7,8,9, few numbers may be skipped

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1024]
This is primarily seen on Dev kits 2

**Comment by beastoin** [comment]
yse bro, on dk2, should be fixed at build +156 - ready on Testflight/Internal Test https://github.com/BasedHardware/omi/releases/tag/v1.0.43%2B156-mobile-cm
