### ISSUE TITLE
Navigation between memories | chat feels buggy sometimes

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1066]
Navigation in some pages overall feels like this
Can we profile this with android or xcode profilers, and decrease it as much as we can?
I have a hunch we have a lot of unneeded ui refreshes.

**Comment by beastoin** [comment]
also, this ?

**Comment by mdmohsin7** [comment]
> also, this ?

Yes sir

**Comment by beastoin** [comment]
should we close this ? pls mention the related PR sir

**Comment by mdmohsin7** [comment]
> should we close this ? pls mention the related PR sir

This one sir #1021

**Comment by beastoin** [comment]
![Image](https://github.com/user-attachments/assets/a380faee-23f2-4147-8cd6-a25dc2b0f554)

do smth like this, next time ;)
