### ISSUE TITLE
Rename plug-ins to apps and move them to  bottom menu to make more visible

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1067]
Plug-ins are our top-1 advantage. We need to move them to bottom menu and make them more visible to users and devs

Also, plug-ins should be renamed to apps, as we need to show to devs that they can build anything with our tech

**Comment by kodjima33** [comment]
![image](https://github.com/user-attachments/assets/443c0401-e14c-40f7-b6af-a5b35cc05be2)

**Comment by beastoin** [comment]
@mdmohsin7 please take it. don't forget to update @kodjima33 , as he might have some great insights to help you finish the ticket well.
