### ISSUE TITLE
Make Events works

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1100]
Events is an Omi's core feature, really weird if we couldn't make it works.

>Sometimes the events don’t get added, sometimes the timing is wrong. I think we shouldn’t add event locally, instead we should add them through Google or Apple APIs, we can ask for user permission for this

\- by @mdmohsin7 

**what**: Fix all above issues, make sure Events work as expected.

**Comment by mdmohsin7** [comment]
Google provides API for Calendar, but Apple does not. There's way to manipulate the iCloud Calendar but is a lot of work due to limitations and restrictions from Apple's side.

We can certainly still implement it on Apple, but is it worth the effort?
https://www.aurinko.io/blog/caldav-apple-calendar-integration/

**Comment by beastoin** [comment]
>Sometimes the events don’t get added, sometimes the timing is wrong. I think we shouldn’t add event locally.

why we shouldn't add them locally? man

**Comment by mdmohsin7** [comment]
> why we shouldn't add them locally? man

We can, and currently we are doing that only. But some users have issues with permissions, for some the calendars don't show up and sometimes it takes time for the event to show up. Thought we could eliminate the issues if we can simply add events to the cloud and the respective calendar apps will sync the events automatically

Maybe we should allow both local and cloud for users to pick from? Adding Google Calendar using API is easy peasy, we will be able to support more calendars in future (Microsoft Outlook)?

**Comment by beastoin** [comment]
>But some users have issues with permissions, for some the calendars don't show up and sometimes it takes time for the event to show up

could we fix these issues?

**Comment by mdmohsin7** [comment]
> could we fix these issues?

Yes can mostly do, will also include a better guide telling the user that it might take time

**Comment by beastoin** [comment]
cool! do it pls sir
