### ISSUE TITLE
from main branch using latest zephyr setup, west build failed with error message , root cause is due to unamed array in negative from transport.c

### ISSUE THREAD

**Issue by cklam12345** [BasedHardware/omi#1113]
#1 **Describe the bug**
#2 firmware_v1.0/src/transport.c:1:
#3 /home/omi/zephyrproject/zephyr/firmware_v1.0/src/transport.c: In function 'accel_start':
#4 /home/omizephyrproject/zephyr/include/zephyr/sys/util.h:97:55: error: size of unnamed array is negative
#5   97 | #define ZERO_OR_COMPILE_ERROR(cond) ((int) sizeof(char[1 - 2 * !(cond)]) - 1)

**Comment by beastoin** [comment]
@cklam12345 could you fix it ?
