### ISSUE TITLE
Make Action Items more useful

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1123]
Currently, action items in memories is just a list of text without any meaningful actions.

**what**: Let make it more useful. be creative.

**random thoughts**: Act as a to-do list, allowing user check/uncheck the action. Daily, weekly remind for the incomplete actions, possibly with chat ?. or just share to a to-do apps?

**Comment by beastoin** [comment]
i have a gift for you, @mdmohsin7 man. Your weekly feature! Let make our Action Items more useful!

**Comment by mdmohsin7** [comment]
<img width="711" alt="Screenshot 2024-10-21 at 5 44 50 PM" src="https://github.com/user-attachments/assets/7e645603-bd7d-47f6-9a22-fc9ee858d0d6">
<img width="721" alt="Screenshot 2024-10-21 at 5 46 13 PM" src="https://github.com/user-attachments/assets/f35c113f-f559-444b-a874-1681d2119763">

**Comment by mdmohsin7** [comment]
> Act as a to-do list, allowing user check/uncheck the action. Daily, weekly remind for the incomplete actions, possibly with chat ?. or just share to a to-do apps?

I think we should do it this way, that is allow users to check/uncheck the action and remind daily at a specific time (if the action item has a time associated with it). But what about the past events? Should we just treat them as completed?

And if want to integrate with any other platform, for iOS we have the Reminders app which already has APIs but what should we be using for Android is a question

**Comment by beastoin** [comment]
>But what about the past events? Should we just treat them as completed?

nope, just leave it as is.

be careful with annoying to-dos reminder.

iOS we have reminder app, what is the similarity in android ?

it would be great if users don't need to open another app (leave Omi app).

**Comment by josancamon19** [comment]
how many people open the memory detail?
why checkable action items would make a difference?
what's the expected user behavior after implementing this?

**Comment by beastoin** [comment]
what is the best way to make Action Items more useful bro? you definitely know better than me, at least for now, then pls help if you have any cool idea for the product 🌚

**Comment by mdmohsin7** [comment]
> why checkable action items would make a difference?

I think it makes sense because they are action items and being able to check/uncheck them means I can be sure that I did complete the task or not. And I guess the prompt has to be more refined to make action items actually actionable

**Comment by mdmohsin7** [comment]
![CleanShot 2024-10-22 at 20 58 10@2x](https://github.com/user-attachments/assets/05aaf3b8-7992-4e12-8ccc-cb35812e32c7)

**Comment by beastoin** [comment]
more reasearch and idea pls sir. take a look at our Daily Norification ability as well.

**Comment by mdmohsin7** [comment]
Things:
- [x] Modify the prompt to have action items only if the user has to do at that moment or in the future, they should not be something the user might have already done or is already doing. This will eliminate a lot of unnecessary action items. For this, taking a bit of inspiration from the `Day Summary` prompt as it has been a lot more accurate.
- [x] Add check/uncheck possibility
- [ ] Integrate Reminders App for iOS (just like the Calendar integration) should we?

The proposal is to make action items as a replacement for the todo apps for the users

**Comment by beastoin** [comment]
don't forget monitor it in the next 2 week, every week. and lmk what we should improve ;)
