### ISSUE TITLE
Not transcribing after device reconnection following a long period of disconnection

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#1124]
<img width="874" alt="Screenshot 2024-10-21 at 12 54 14 PM" src="https://github.com/user-attachments/assets/28143c95-710a-4139-ae0d-4c749a811492">

Was able to reproduce the listening issue.
Steps:
1/ Connect device
2/ Go out of reach of the phone and stay there for at least 4-5 minutes
3/ Come back near the phone, device will connect automatically
4/ Try speaking, no transcript will appear, even though it shows listening
5/ Disconnect and reconnect the device, still no transcript will appear
6/ Close and then open the app, transcript appears

**Comment by beastoin** [comment]
tested, the transcript've just picked up when i came back. backend > socket related issue - i guess. close for now :)
