### ISSUE TITLE
A simple way to add/submit apps (plugins)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1128]
**Is your feature request related to a problem? Please describe.**
People want to be able to test their plugins on their local mobile phone without the need to build the app. 
I went on multiple omi hackathons recently and people were really frustrated with the fact that they need to wait until someone approves their plugin to test on the mobile app. 
Currently, there is no option to test my own plugin in the app without forking and building locally. 

**Describe the solution you'd like**
We need to build a simple form that would allow people to submit their apps through the form. We can host the form on the web / in the omi app. Once submitted, the submitted app should be available to test locally RIGHT AWAY in omi. However, the app will not be available for all users right away and Omi team will need to review it (like we do it now in community plugins) 
- available for submitter right away
- available for everyone else once approved by omi team

**Comment by mdmohsin7** [comment]
Solution based on my personal thoughts:
Move plugins data from the community-plugins.json file to Firebase (as a separate collection). Then provide a screen in the app for the user to create a plugin. Once they submit it, the plugin will be under review unless someone from the team approves it. While still being in review, the plugin will be usable by the creator themself. Once approved, everyone will be able to use it. This also enables the ability to have private plugins, users can select an option (on the screen) from the dropdown whether to make the plugin private or public.

This is just based on what I think would be a good approach in terms of keeping the UX simple.

**Comment by mdmohsin7** [comment]
> Solution based on my personal thoughts: 
Move plugins data from the community-plugins.json file to Firebase (as a separate collection). Then provide a screen in the app for the user to create a plugin. Once they submit it, the plugin will be under review unless someone from the team approves it. While still being in review, the plugin will be usable by the creator themself. Once approved, everyone will be able to use it. This also enables the ability to have private plugins, users can select an option (on the screen) from the dropdown whether to make the plugin private or public.
> 
> This is just based on what I think would be a good approach in terms of keeping the UX simple.

Planning to go with this approach, @kodjima33 @thinhx lmk what do you guys think of it

**Comment by kodjima33** [comment]
@mdmohsin7 sounds great to me. Not sure if removing community plugins json is great long-term. If @josancamon19 and @thinhx think it's good idea, you should start

**Comment by beastoin** [comment]
nice to see you want to help Mohsin!

go with Firestore. we always need a database stay behind a rich(complicated) feature.

btw please focus on: How does the system work with the new state of Apps(as a sandbox). I would need to take a look at the system design or at least the sequence flow. Feel free to lmk when we have it.

**Comment by mdmohsin7** [comment]
This approach is only to move the json file to firestore, so in theory everything will stay the same architecture wise, only the source of the data changes. I did not exactly see how Adam is implementing apps but I am assuming through json only (as external integrations), so they should work just fine as well. The proposal is to convert the PR adding way to a UI way with additional fields like `is_approved`, `is_private` etc

Will ping you when I draft a final plan with the sequence flow and stuff

**Comment by josancamon19** [comment]
https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=83851149

Will remove this one then, as I guess that will be don ehere

**Comment by sanjayamirthraj** [comment]
Working on this!

**Comment by mdmohsin7** [comment]
<img width="1004" alt="Screenshot 2024-10-30 at 12 17 35 AM" src="https://github.com/user-attachments/assets/51dae549-0f25-4655-8cf2-36a24fc3ea1f">


Doc structure for both private and public apps
```
{
  "id": "xyz-123",
  "name": "app-name",
  "author": "mohsin",
  "author_id": "abc123efg456",
  "description": "this app does xyz",
  "image": "https://firebase-storage-link",
  "capabilities": ["memories", "chat", "external"],
  "memory_prompt": "this is conditional",
  "chat_prompt": "this is conditional",
  "deleted": false,
  "approved": true,
  "private": false,
  "external_integration": {
    "triggers_on": "transcript_processed",
    "webhook_url": "https://example.com/news-checker",
    "setup_completed_url": "https://example.com/done",
    "setup_instructions": "https://example.com/how-to-use"
  }
}
```

App Triggers:
<img width="860" alt="Screenshot 2024-10-30 at 12 15 32 AM" src="https://github.com/user-attachments/assets/b6e0882b-9d9d-4831-9796-56c24bbd8460">

**Comment by beastoin** [comment]
@mdmohsin7 @sanjayamirthraj how's it going mans?

**Comment by sanjayamirthraj** [comment]
I think we should have it done in around 5 days? We are attempting to restructure the plugins format

**Comment by mdmohsin7** [comment]
Hopefully will be done in 2-3 days 😉

**Comment by josancamon19** [comment]
https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=84453410&issue=BasedHardware%7Comi%7C1154

**Comment by beastoin** [comment]
@mdmohsin7 quick recap pls then we move to the next phrase. 

we might need to split this task then roll out the new one.

**Comment by mdmohsin7** [comment]
It indeed was a lot more work than I thought XD

Progress:

- [x] Users can successfully submit public and private apps from within the Omi App
- [x] Once the apps are approved, if it's a memory app, then it will be triggered correctly
- [x] User can enable the newly added chat app and chat with it (once approved)
- [x] To be able to trigger unapproved and private apps
- [x] Cache public plugins

@beastoin I've attached some videos in #1232 
The only thing that is left for the 1st phase is the triggers part.

Next Phase:
- Change visibility of Apps from UI
- Delete Apps from UI
- Better segregation of private apps from public apps
- Revamp Apps UI
- Make external triggers more modular (ability to specify the exact datapoints they need like summary, action items, transcript etc)

**Comment by beastoin** [comment]
>To be able to trigger unapproved and private apps, I will have to modify the Plugin Model to include new fields (private, approved) with default values. Should I? (this is the only thing that is pending)

what is this for man ?

just limits max 3 users for a private app.

**Comment by mdmohsin7** [comment]
> what is this for man ?
> 
> just limits max 3 users for a private app.

That is to be able to use plugins without them being approved

**Comment by beastoin** [comment]
> To be able to trigger unapproved and private apps, I will have to modify the Plugin Model to include new fields (private, approved) with default values. Should I? (this is the only thing that is pending)

you could simplify it by removing the `private` field, either keeping `approved` or even getting rid of it. you already have `/users/:id/apps` for the private apps + `/apps/` for the public+approved apps. 

the important things to consider are:
1/ ensure the old app(iOS/Android) version work, so let's upgrade the plugin API to +1 version while maintaining the logic with github json file for the old ver. you wouldn't need to deal with the img > src as well haha.
2/ the review submission flow must be simple. So, who would have the permission to approve apps and how would they know when new apps need approved ? 


@mdmohsin7 ~ overall good progress btw not fast enough haha

**Comment by mdmohsin7** [comment]
1/ Yes that is what I am doing, created new routes. There are some routes which depend on the plugins data, like the memories route, it has a function `_trigger_plugins` which calls `get_plugins_data`. Should I create a completely new route for memories just so that it can use the new `get_plugins_data_from_db` or directly use `get_plugins_data_from_db` in the existing route? This should not have much effect as only the name, prompt and webhook URLs (if any) from that plugin is used and these things are same for both `get_plugins_data_from_db` and `get_plugins_data`

2/ The review process I am considering at the moment is when a plugin is submitted, a message will be sent on discord, and I'll simply curl the approve url with the plugin id. The team will be approving the apps

I hate dynamic languages hence not so fast progress haha. Jokes aside there were things I didn't new in our backend lol so it took some time to figure out the flow of each route

@beastoin

**Comment by mdmohsin7** [comment]
All in all, I should have the PR ready for review by EOD

**Comment by beastoin** [comment]
1/ new router means new routers. haha. the idea is the old app would see plugins from json file. that's all. the new plugin logic will affected for deeper logic layers e.g. utils, db
2/ oops. what about create a new PR to Github > plugin json file ? looks like json file is the source of truth haha, then we don't need the `/apps` as well 😏

anw, just gimme a PR by EOD @mdmohsin7 looking fwd

**Comment by sanjayamirthraj** [comment]
Accidentally unassigned myself if someone could add me back

**Comment by mdmohsin7** [comment]
1/ I got it, don't know why I did not think of this lmao
2/ It was the source of truth, but we are moving it to firestore right. Plus there isn't an easy way to open a PR with changes through GitHub API

Guess I don't have to modify the Plugin model, the apps will still be triggered now (even if unapproved) if the user has enabled them

@beastoin

**Comment by mrkilvish** [comment]
I am submit a apps but my apps is still in pending for reviewing
