### ISSUE TITLE
Add hyperlink "build your own app" to apps list in Omi app

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1154]
Add it to the top of the list and at the bottom
Link should lead to omi.me/apps/introduction

![image](https://github.com/user-attachments/assets/09cc2eda-b949-4b89-8504-e193cd510fe0)

**Comment by aalberti333** [comment]
Happy to pick this up if that's okay 🙂 do I need to be assigned? Or can I fork and just start working it?

**Comment by kodjima33** [comment]
This should be merged with #1128
