### ISSUE TITLE
Request: let apps respond with Markdown

### ISSUE THREAD

**Issue by findirfin** [BasedHardware/omi#1161]
Right now it is kind of hard to read the plugin responses, especially if they are long or have lists. Letting them respond with markdown formatting could solve this issue.

**Comment by smian1** [comment]
I agree with this. I was just thinking about the formatting. MD support would be great. I would like to see support for bullet points, numbers, checkboxes, and so on.

**Comment by beastoin** [comment]
@josancamon19 is it working man? if yes pls close it.
