### ISSUE TITLE
dev kit 2 battery drain

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1193]
Dev kit 2 battery drain is 36% if left per night

should be 0

**Comment by beastoin** [comment]
![Image](https://github.com/user-attachments/assets/8f3458e3-ac22-41cd-910e-6066258b12fc)

**Comment by kevvz** [comment]
#1160 

 I measured the current, it is 1.3 mA now, so over 150 hours of deep sleep is possible. Overnight it should be no more than 5 percent
