### ISSUE TITLE
Uptime page

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1196]
I want to see an uptime page like [this ](https://www.google.com/search?q=site+uptime+page&sca_esv=3ba6c21c49c51756&udm=2&biw=1587&bih=1134&sxsrf=ADLYWIK8zEN7bqtg5xbW_AMSDZjRq0Cv3Q%3A1730088771642&ei=Qw8fZ6_2JpSu0PEPspT3sAo&ved=0ahUKEwjvo6f1mrCJAxUUFzQIHTLKHaYQ4dUDCBA&uact=5&oq=site+uptime+page&gs_lp=EgNpbWciEHNpdGUgdXB0aW1lIHBhZ2VI0xxQmAVYpBtwA3gAkAEAmAF2oAGnCqoBBDEzLjO4AQPIAQD4AQGYAg6gAu4HwgIGEAAYCBgewgIKEAAYCBgKGB4YD8ICCBAAGAgYChgewgIEECMYJ8ICCxAAGIAEGLEDGIMBwgIKEAAYgAQYQxiKBcICDhAAGIAEGLEDGIMBGIoFwgIIEAAYgAQYsQPCAg0QABiABBixAxhDGIoFwgIKEAAYgAQYsQMYCsICBxAAGIAEGArCAgUQABiABMICBBAAGB7CAgYQABgeGA_CAggQABgFGAoYHsICCBAAGAUYHhgPwgIIEAAYCBgeGA-YAwCIBgGSBwQxMS4zoAf5RQ&sclient=img#vhid=z0pPyUb1J87guM&vssid=mosaic)

We will put that page as a link on our landing page omi.me 

On that page we need to show: 

- up-time of transcription 
- up-time of api (real-time transcription, real-time audio, memories)

**Comment by beastoin** [comment]
man @mdmohsin7 pls check the email from instatus.com . you could try it with integration Google Cloud Monitoring

**Comment by mdmohsin7** [comment]
You've already added the webhook I guess (that is what I can see in the dashboard)? Is there anything that is left in this? Should I create the uptime endpoints?

**Comment by beastoin** [comment]
https://omiai.instatus.com/ does it work?

**Comment by beastoin** [comment]
https://p.us5.datadoghq.com/sb/8c9ed44d-9370-11ef-86c8-faa22449e9db-e82497c0119c6ce8fc9d1ce3f85cd5f7

**Comment by beastoin** [comment]
```
<iframe src="https://p.us5.datadoghq.com/sb/embed/8c9ed44d-9370-11ef-86c8-faa22449e9db-e82497c0119c6ce8fc9d1ce3f85cd5f7" title="Dashboard Name" width="800" height="800"></iframe>
```

**Comment by beastoin** [comment]
![Image](https://github.com/user-attachments/assets/db0e1844-b9d0-4b29-a2bb-829bfd9ffa42)

if the heartbeat goes flat then we die

**Comment by beastoin** [comment]
http://status.omi.me
