### ISSUE TITLE
Require auth for /listen API

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1236]
I don't want anyone be able to access to the socket with a simple call wscat to /v2/listen API.

please add auth to that api

**Comment by beastoin** [comment]
@nquang29 welcome to the party. yours.

**Comment by vincentkoc** [comment]
FYI possible breaking changes on #1238 - easier to add my changes as some of the auth is tested there.

**Comment by nquang29** [comment]
MR:
- [add auth for v2/listen](https://github.com/BasedHardware/omi/pull/1355/files)

**Comment by beastoin** [comment]
> MR:
> 
> - [add auth for v2/listen](https://github.com/BasedHardware/omi/pull/1355/files)

comments sent

**Comment by beastoin** [comment]
it works great, thanks @nquang29
