### ISSUE TITLE
Change source of truth for Omi Apps on Web

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#1266]
Change the endpoint for https://h.omi.me/apps to use the latest one (which fetches plugins from firebase)

**Comment by kodjima33** [comment]
Need this done

**Comment by beastoin** [comment]
@mdmohsin7 @smian1 also have some great ideas for improving the apps page. looking fwd for your collaboration 🥳

**Comment by beastoin** [comment]
https://github.com/BasedHardware/omi/actions/runs/11885703139/job/33115784693

Deploy failed.

\---
#19 46.32    Skipping validation of types
#19 46.32    Skipping linting
#19 46.60    Collecting page data ...
#19 48.11    Generating static pages (0/10) ...
#19 49.56    Generating static pages (2/10) 
#19 49.57    Generating static pages (4/10) 
#19 49.68    Generating static pages (7/10) 
#19 50.26 TypeError: t.sort is not a function
#19 50.26     at c (/app/.next/server/app/apps/page.js:1:3102) ***
#19 50.26   digest: '3919056425'
#19 50.26 ***
#19 50.26 TypeError: t.sort is not a function
#19 50.26     at c (/app/.next/server/app/apps/page.js:1:3102) ***
#19 50.26   digest: '3919056425'
#19 50.26 ***
#19 50.26 TypeError: t.sort is not a function
#19 50.26     at c (/app/.next/server/app/apps/page.js:1:3102) ***
#19 50.26   digest: '3919056425'
#19 50.26 ***
#19 50.26 
#19 50.26 Error occurred prerendering page "/apps". Read more: https://nextjs.org/docs/messages/prerender-error
#19 50.26 
#19 50.26 TypeError: t.sort is not a function
#19 50.26     at c (/app/.next/server/app/apps/page.js:1:3102)
#19 51.99  ✓ Generating static pages (10/10)
#19 52.00 
#19 52.00 > Export encountered errors on following paths:
#19 52.00 	/apps/page: /apps
\---

**Comment by mdmohsin7** [comment]
Did not see this (although it worked locally), will check and make changes. Maybe we will deploy it alongside deep linking for sharing #1345

**Comment by beastoin** [comment]
@mdmohsin7 what do you think about solving this problem first then we close the ticket 😌

**Comment by mdmohsin7** [comment]
> @mdmohsin7 what do you think about solving this problem first then we close the ticket 😌

Sure haha! Let me try
