### ISSUE TITLE
discord.omi.me redirects to an expired invite 

### ISSUE THREAD

**Issue by henrygagnier** [BasedHardware/omi#1287]
**Describe the bug**
discord.omi.me (found in [app/setup.sh](https://github.com/BasedHardware/omi/blob/20fc6a83431c048ceeec987d7cc16274192290c5/app/setup.sh#L18)) redirects to an invalid invite.

**To Reproduce**
Enter discord.omi.me into any browser.

**Current behavior**
discord.omi.me redirects to https://discord.com/invite/based-hardware-1192313062041067520 which is invalid on my end.

**Expected behavior**
discord.omi.me redirects to a valid invite (such as https://discord.gg/8MP3b9ymvx, found on the website)

**Screenshots**
![image](https://github.com/user-attachments/assets/d746c25d-999b-421f-9ce3-c35706b994c9)

**Comment by beastoin** [comment]
<img width="696" alt="Screenshot 2024-11-12 at 11 31 00" src="https://github.com/user-attachments/assets/d187aedf-4f39-4cb2-b52e-48697b39ef00">

Cool @henrygagnier , the issue should've been fixed.
