### ISSUE TITLE
Dashboard to approve apps

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1289]

**Comment by beastoin** [comment]
Now we could sort the plugin by created at via Firestore ![Image](https://github.com/user-attachments/assets/5bce87d2-6b72-4baf-9bc1-dceaa777dac4)

This task is not super important, btw if you could complete it quickly like 2 hours, so pls go ahead. otherwise, we just move back to the No status for the future consideration.

@mdmohsin7 / @sanjayamirthraj

**Comment by mdmohsin7** [comment]
@smian1 already created an MVP for it

**Comment by beastoin** [comment]
@smian1 looking fwd.

**Comment by beastoin** [comment]
Salman did it 🥳 +1 @smian1
