### ISSUE TITLE
Merge Apps/Plugins Terms

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1290]
merge 2 terms app / plugin + should be done in the next 2 weeks

**Comment by beastoin** [comment]
not super important, take your time Mohsin.

**Comment by beastoin** [comment]
close ? should i

**Comment by mdmohsin7** [comment]
Can be closed, we are in the final stages of the merge (that is removing the old endpoints but we will do this after few more versions of the app)

**Comment by beastoin** [comment]
ok coo, just leave a comment e.g. @deprecated, dont need to remove it from the code.
