### ISSUE TITLE
Change Proactive Notification to Notification when creating a new app

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1297]
Change `Proactive Notification` to `Notification` when creating a new app

Open Omi app > Apps > Create your own app

## TODOs

- [x] Change Proactive notification  -> Notification
- [x] Change Proactive Notification Scopes -> Notification Scopes

## Refs
![IMG_7856](https://github.com/user-attachments/assets/31e974b7-797c-4843-8688-bc30dcfd0ef0)

![IMG_7855](https://github.com/user-attachments/assets/ff33a046-2b78-447d-838b-bb130926b202)

**Comment by beastoin** [comment]
@chiemduong97

**Comment by beastoin** [comment]
@nquang29 follower pls / Duong lead

**Comment by chiemduong97** [comment]
- todo:
 + BE: api 'v1/app-capabilities': change Proactive notification -> Notification
 + App:  change title:  Proactive Notification Scopes -> Notification Scopes

**Comment by beastoin** [comment]
PRs(1/2):
- https://github.com/BasedHardware/omi/pull/1310

**Comment by nquang29** [comment]
PRs(2/2): 

[add notification & rename title app capablilities](https://github.com/BasedHardware/omi/pull/1318)  #1318
