### ISSUE TITLE
Apps don't have access to facts/conversations (and they should have)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1306]
**Describe the bug**
when im chatting with omi, it's smart. when im chatting with an app, it's dumb (doesn't have access to facts) 
![Image](https://github.com/user-attachments/assets/670b92d1-7d92-4891-b7bb-a5b06bc3cbb8)

**Current behavior**
apps don't have access to conversations/facts

**Expected behavior**
apps should have same access as default omi's chat persona

**Comment by kodjima33** [comment]
seems to be working now but not sure

**Comment by beastoin** [comment]
yes it works :)
