### ISSUE TITLE
Dupplicated notification occurs whenever the app is openned(not minimize or in background mode) on iOS

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1309]
Dupplicated notification occurs whenever the app is openned(neither minimize nor in background mode) on iOS

**To Reproduce**
1. Open Omi app, keep it opened
2. Install App `Mentor.01`
3. Says 'Hey Omi what do you think`

**Current behavior**
There're 2 notifications occurs

**Expected behavior**
Only one notification

**Screenshots**

![IMG_7880 Large](https://github.com/user-attachments/assets/7d62a24e-babf-4dcc-adbb-107d5280e9f6)
![IMG_7881 Large](https://github.com/user-attachments/assets/1b654756-5b2d-4199-8aff-f843a0598733)

**Smartphone + device**
 - Device: iphone 11 pro
 - App Version: 1.0.46 build 170
 - Device version: DevKit 2 - firmware 2.0.2

**Comment by beastoin** [comment]
@nguyenthe0107

**Comment by kodjima33** [comment]
still getting this bug

**Comment by beastoin** [comment]
done, try it now b177
