### ISSUE TITLE
for [notification] capability, we need to pass conversations as well

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1313]
**Is your feature request related to a problem? Please describe.**
currently, when using [notification] capability, as a developer, im not able to pass {conversations} as a parameter and I really want to 

**Describe the solution you'd like**
I want to have {conversations} (memories) as a parameter to pass along with {facts}

For example I'm building a personal mentor app and the mentor's advice is very dumb if it doesn't know what has been happening in my life recently

**Comment by beastoin** [comment]
## Status
- ready on production

## Usage
- Enable scopes `user_context` (named as User memories in Omi app)
- In the webhook, respond with model: 
    ```
    {
      ...
      "notification": {
        "prompt": "this is a system instruction with the {{user_context}} string. you could also include {{user_name}} and {{user_facts}} as well.",
        "params": [
          ...
          "user_context"
        ],
        "context": { # optional
          "filters": {
            "people": [], 
            "entities": [],
            "topics": []
          }
        }
      }
    }
    ```

**Comment by beastoin** [comment]
issues: #1132
