### ISSUE TITLE
There're no User facts, User name scopes when updating an app

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1322]
There're no User facts, User name scopes when updating an app

**To Reproduce**
1. Open Omi App then open your app
2. Click to Setting Icon, choose Update App Details
3. Choose Notification capacity

**Current behavior**
There're no Notification scopes such as user facts, user name

**Expected behavior**
Include Notification scopes so that user could update the app's scope as well. Same with the create new app feature.

**Screenshots**
- Actual:
  ![IMG_7893 Large](https://github.com/user-attachments/assets/4ccfa953-4045-416d-9fd6-98d9b4c78740)

- Expected:
  ![IMG_7892 Large](https://github.com/user-attachments/assets/48c3d149-0b60-4752-b8e4-e0e36c855508)

**Smartphone + device**
 - App Version: 1.0.46 build 170

**Comment by beastoin** [comment]
@chiemduong97

**Comment by mdmohsin7** [comment]
This is enabled/disabled from the backend right?

**Comment by chiemduong97** [comment]
PRs [add Notification Scopes to updating an app](https://github.com/BasedHardware/omi/pull/1325) #1325

**Comment by chiemduong97** [comment]
> This is enabled/disabled from the backend right?

yes
