### ISSUE TITLE
When chatting with apps, it doesn't keep track of context

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1323]
**Describe the bug**
I receieved a proactive notification from the app i built "test mentor". It gave me useful advice based on current conversation and asked if I want to "dive deeper" 
When I said yes, it instead switched the topic to some random conversation 

**To Reproduce**
Receive a proactive notification from any custom app
ask a followup question

**Current behavior**
Switches to a different topic, instead of continuing on the last message

**Expected behavior**
If I ask followup question for a chat's message, Continue the conversation for the same topic

**Screenshots**
![Image](https://github.com/user-attachments/assets/662cf468-3d87-4603-8819-03c6f305a286)

**user ID (can we access the user info to validate the bug?):**
viUv7GtdoHXbK1UBCDlPuTDuPgJ2

**Smartphone + device (please complete the following information):**
1.0.46 + 170

**Comment by Pankajkumar2608** [comment]
I can help in this. I would like to slove this problem.

**Comment by beastoin** [comment]
hey @Pankajkumar2608 any updates ?

**Comment by beastoin** [comment]
removed, no updates 😌 / maybe next time man

**Comment by beastoin** [comment]
done, pls try 🚀
