### ISSUE TITLE
Real-Time Notification Update Bug in Chat Functionality

### ISSUE THREAD

**Issue by smian1** [BasedHardware/omi#1329]
**The chat functionality in the Omi app displays notifications but does not update them in real-time.** Users have to force close the app and reopen it to view the latest notifications in the chat, which disrupts the user experience. Currently, only partial notifications are visible until the app is refreshed.

Enabling real-time chat updates would greatly improve user experience by ensuring notifications appear seamlessly without manual intervention. This is especially crucial for lengthy notification alerts, as only the first part is visible initially. Users wanting to see the full details by tapping on the notification and navigating to the chat cannot do so without restarting the app.

**Comment by beastoin** [comment]
duplicated #1328
