### ISSUE TITLE
RangeError Index Handling issue

### ISSUE THREAD

**Issue by smian1** [BasedHardware/omi#1343]
Getting an error when deleting an app. App seems to be deleted, but this error shows up. 

![image](https://github.com/user-attachments/assets/e9533cd1-ba64-4888-91d8-8fca711d4163)

**Comment by smian1** [comment]
@mdmohsin7

**Comment by mdmohsin7** [comment]
![image0](https://github.com/user-attachments/assets/643927d2-0927-4358-948e-fdc362cd2c34)
