### ISSUE TITLE
Every app should have a sharable web link

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1345]
As an app/plugin developer, when i create a new app, i immiedeatly want to share it with my friends to promote it. 

In app settings, i want to get a web url (copyable) that i can share in Discord/messages so that people could use my app directly. 

idealy if it works for both cases: 
- for people who didn't yet download main omi ai app
- for people who already downloaded

**Comment by mdmohsin7** [comment]
Shareable link: h.omi.me/apps/{app_id}

Makes sense I guess? It's the easiest and fastest

**Comment by beastoin** [comment]
what about try.omi.me/apps/{app_id} ?

**Comment by mdmohsin7** [comment]
That works as well. We should have a fixed domain so that we can setup dynamic links right from the beginning

**Comment by beastoin** [comment]
@chiemduong97 pls try to solve this ticket

fyi we already have the webpage for an app e.g. https://h.omi.me/apps/conversation-summarizer , code repo: https://github.com/BasedHardware/omi/tree/main/frontend - a NextJS project

**Comment by kodjima33** [comment]
Guys this needs to be done faster

**Comment by beastoin** [comment]
got it bruh. let me.

@chiemduong97 please note the step you are on so that i can help.

**Comment by mdmohsin7** [comment]
Lmk if any help is needed. Setting up apple-app-site-association and assetlinks.json files on the web and adding the schemas to open the links on Android and iOS (and also link handling) should be enough I guess for the initial version

**Comment by beastoin** [comment]
go ahead and get this ticket done pls sir.

pls note: 
- support domains h.omi.me and try.omi.me
- only allow /apps/:id for now, so that users can access the webpage when they enter h.omi.me/apps or h.omi.me for example - this should be configurated via the json file (Google applink or apple association json)

@mdmohsin7 ⚡️

**Comment by mdmohsin7** [comment]
Alright let me try

**Comment by beastoin** [comment]
2/ 'Try it' should navigate user to the app screen or appstore/gplaystore


![Image](https://github.com/user-attachments/assets/23cfddf8-baec-4bb6-86ba-06d82d1c1fe8)

**Comment by beastoin** [comment]
3/ App got crashed when opened from the weblink

link: https://h.omi.me/apps/zapier

 ![Image](https://github.com/user-attachments/assets/9aa2d151-67a1-4d5b-888c-e92e1d786d03)

**Comment by chiemduong97** [comment]
issue on android device 
https://stackoverflow.com/questions/58596267/flutter-app-opens-in-another-applicationduplicate-application

**Comment by mdmohsin7** [comment]
> 3/ App got crashed when opened from the weblink

Checked Instabug, this looks like an issue with `flutter_background_service`
`SInternalInconsistencyException: No launch handler registered for task with identifier dev.flutter.background.refresh`
