### ISSUE TITLE
Use mget to get apps installed count / reviews instead of loop - Dont loop in infra

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1353]
Redis rps is ~ 400/s now and would keep increasing to indefinitely base on the number of apps.

dont loop in infra

use mget

![Image](https://github.com/user-attachments/assets/62078138-074a-4e9e-a26d-6b51368c61f2)

![Image](https://github.com/user-attachments/assets/639c423f-d0be-41e4-916d-78906604f7db)

**Comment by beastoin** [comment]
@nquang29 let's see if you're still remember basic techniques 🌚

**Comment by beastoin** [comment]
context: we are facing with 1/ high p99 latency with api /apps 2/ high costs due to too many tracing spans in Datadog

pls help me resolve these 😌

thank you!

**Comment by nquang29** [comment]
> @nquang29 let's see if you're still remember basic techniques 🌚

let me see

**Comment by nquang29** [comment]
MR:
[using mget when get plugin review/install for /apps](https://github.com/BasedHardware/omi/pull/1385)

**Comment by beastoin** [comment]
### ops change logs
1. feature on prod 🚀 

@nquang29 fyi ~

**Comment by beastoin** [comment]
before | after 
![Image](https://github.com/user-attachments/assets/3dd367ff-1d85-4503-b240-7ce875bf9e0a)

saving x10

**Comment by beastoin** [comment]
anw dont forget leave a check at the mget limits, e.g. what is the maximum keys / request ? @nquang29
