### ISSUE TITLE
UI Requests

### ISSUE THREAD

**Issue by henrygagnier** [BasedHardware/omi#1387]
Some very very minor things I noticed when using the app

1.) Long app names are cut off
2.) There is no margin on the right of the search bar
3.) Boxes don't include long categories names
4.) Reviews are placed below box in Popular Apps
5.) Category names would look cleaner as "Productivity and Organization" instead of hyphenated (opinion) 
6.) Logos are cut off slightly
![image](https://github.com/user-attachments/assets/d2d8ac5b-0acf-4209-a73b-9df996eded49)
![image](https://github.com/user-attachments/assets/5c5f7c9d-50bc-4555-aaa8-dfc74cc456be)

This is on an iPhone SE 2

**Comment by henrygagnier** [comment]
@mdmohsin7 
I just noticed that I am also unable to select User Memories in Nofication scopes on iPhone SE 2 because App Privacy covers it.
![image](https://github.com/user-attachments/assets/efb2be59-d13f-4d2a-8166-8bb4746693f9)

**Comment by mdmohsin7** [comment]
Hi @henrygagnier, thanks for pointing it out, I've fixed it already 😉
