### ISSUE TITLE
make "hey omi" core functionality of the app ($1000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1388]
we built "hey omi" as an app and even though it's bad code, people really want to use it
we need to make it core funcitonality of the product but with few changes:

1. "hey omi" should be triggered with a long press of the button on the omi device and the query should be collected while the user is holding the button.
2. turnon/turnoff of the device should be switched to short click 
3. after the button is released, we send the question/prompt to LLM, while passing all {facts} and {conversations/memories}, chat history and current conversation 
4 the answer should be shown in the chat and sent via notification 

This is a paid task. Reward is $1000 in cash. Simply link your PR to this issue to receive the money

**Comment by Pethousesmart** [comment]
El sistema "Hey Omi" podría ser muy valioso en el ámbito médico, especialmente durante procedimientos quirúrgicos. Los doctores podrían utilizar el sistema para:

1. Registrar sus pensamientos y observaciones durante la operación.
2. Generar un resumen de los pasos realizados y las decisiones tomadas.
3. Documentar cualquier complicación o incidente que ocurra durante la operación.
4. Crear un registro detallado de la operación para futuras referencias.

Esto podría ser especialmente útil en situaciones como:

- Operaciones complejas que requieren una gran cantidad de información y decisiones rápidas.
- Procedimientos quirúrgicos que involucran múltiples especialistas y equipos.
- Casos de emergencia donde la documentación y la comunicación son críticas.

Además, el sistema podría ser integrado con otros sistemas de registro médico para crear un historial completo y preciso del paciente.

**Comment by gluonparticle** [comment]
Do you want the "Hey omi" to be triggered only for answering certain questions which the user has? 

And you wanna trigger "Hey Omi" for long presses (Answering questions given while the user is holding) , and the usual funcitonality for clicks? ;
