### ISSUE TITLE
FIX FACTS

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1422]
- [x] - 1st issue: 2 weeks ago I had 100 facts. Today I still have 100 facts. (see pics as proofs)
- [x] - 2nd issue: facts should be not just about what I like 

More context: 
Current facts collected about the user are some AI-generated bullshit like "Nikita is interested" or "Nikita enjoys"

As a developer, when using facts, I'm not even able to extract useful information such as "city of living", "age", etc...

**Describe the solution you'd like**
I want facts to contain actually useful information such as
Age, city of living, marriage status, health, friends names, relationships, preferences, allergies. Imagine an FBI report on a person - that's exactly how it should be.

Pics
![Clipboard 26 Nov 2024 at 22 36](https://github.com/user-attachments/assets/853b6709-b5a2-4a89-8f63-bdbc95220942)
![IMG_3522](https://github.com/user-attachments/assets/9f078b41-4065-457f-b9bc-6b2355d23221)

**Comment by josancamon19** [comment]
![CleanShot 2024-11-27 at 13 43 11@2x](https://github.com/user-attachments/assets/2db3abcb-cab6-4c24-9472-6cbb697b9c8a)

Doesn't seem to have stopped creating new facts, even Salman is getting new ones.
But it will not add new facts if feels like it's repeating itself with stuff already knows about you.

**Comment by josancamon19** [comment]
For context:

![Image](https://github.com/user-attachments/assets/3f2b475a-0433-41c4-8963-2b01a9c6b478)

**Comment by josancamon19** [comment]
I see you again have 100 facts, but they seem to be on different categories?

**Comment by josancamon19** [comment]
In COMPLETELY different categories, wtf? why? how? was this after you changed the prompt? did you clean up your facts?

**Comment by josancamon19** [comment]
I understand habits, lifestyle, hobbies are really few or none, but can you provide with a few conversations examples, and provide this one should include this facts.

Or how facts should be determined? for example, unless you have said that you live in San Francisco, it will prob not determine that you live there, as that'd be an inference based on your conversations, not a fact.

**Comment by kodjima33** [comment]
@josancamon19 no bro didn't delete but hahaha today I reopened the app, my facts got reshuffled into different categories  again :D 

I just opened again, I have still 100 but now it's 
1 hobby
11 interests
71 work
5 other
1 skill
11 lifestyle

**Comment by josancamon19** [comment]
I just pushed to prod test in 20 min, you should have like 2.5k facts, is bad for other reasons, but it should be better, lmk.

**Comment by josancamon19** [comment]
Check 2) again if you have facts like those you put as example

**Comment by josancamon19** [comment]
@beastoin moved this to in-review, please check [this file](https://github.com/BasedHardware/Friend/blob/f1251f9995bea9d74e335206f37a04a6d0c9be69/backend/scripts/rag/facts.py)

Run it with your id, and check how the facts results improved compared to previous ones.

**Comment by josancamon19** [comment]
I can confirm this part was executed:
![Image](https://github.com/user-attachments/assets/364cfaef-09fe-46a9-ad95-6f0b6cf7f133)

**Comment by josancamon19** [comment]
Should we filter |||| As a developer, when using facts, I'm not even able to extract useful information such as "city of living", "age", etc... |||| only "core" facts into apps prompts?

**Comment by beastoin** [comment]
https://docs.google.com/spreadsheets/d/1DMc4GjJTc0JzkY6tWHC0PV-z9T2zzZXFyLppKN_gAAQ/edit?gid=1103725368#gid=1103725368 my facts 


at core - 44/58 - 75% good.

they covered my living, age, marriage status, family, experiences, ...

**Comment by beastoin** [comment]
<img width="555" alt="Screenshot 2024-11-30 at 18 38 51" src="https://github.com/user-attachments/assets/ae320c55-984e-403b-a394-0b7074554115">
there's some duplicated facts at core, e.g. ^

**Comment by beastoin** [comment]
> Should we filter |||| As a developer, when using facts, I'm not even able to extract useful information such as "city of living", "age", etc... |||| only "core" facts into apps prompts?

should we pick 25 facts each category, or go with some ratio e.g. 50:20:10:10:10

**Comment by josancamon19** [comment]
Thanks for the feedback

**Comment by josancamon19** [comment]
75% seems really good to me

**Comment by josancamon19** [comment]
They can be duplicated, because the scripts runs in parallel sometimes :c otherwise it would take too long

**Comment by josancamon19** [comment]
But on generated memories, it should not generated any duplicated facts

**Comment by beastoin** [comment]
@josancamon19 pls help me by noting down steps to deploy. to ensure the current app/backend fully functional e.g:
1. release the app
2. wait for 100% user updates 
3. release backend
4. run the migration xyz

and, are there any breaking changes affecting the current mobile apps ?

**Comment by beastoin** [comment]
follow up https://github.com/BasedHardware/omi/pull/1483

**Comment by beastoin** [comment]
<img width="814" alt="Screenshot 2024-12-06 at 18 58 55" src="https://github.com/user-attachments/assets/9d08f167-d90e-48d0-8602-ef395985a0ef">

are you ready sirs ?

**Comment by beastoin** [comment]
<img width="613" alt="Screenshot 2024-12-07 at 12 59 41" src="https://github.com/user-attachments/assets/d3618b61-96ec-4bee-9290-0377bc30640e">
lfg wohooo

**Comment by beastoin** [comment]
### Product changes logs
- ready on Testflight / Internal test 🥳

@kodjima33 fyi ~ bro, please take a look at your Facts and feel free to let me know.
