### ISSUE TITLE
Small Screen UI issues

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#1475]
https://github.com/user-attachments/assets/bd2bbb56-98ba-45c9-81d8-e26999ee1a5d

**Comment by beastoin** [comment]
<img width="370" alt="Image" src="https://github.com/user-attachments/assets/f1b2dd1f-c97e-44c0-b876-d905713bf448" />
oh my eyes, look at these stars padding

**Comment by mdmohsin7** [comment]
> oh my eyes, look at these stars padding

Haha fixed in #1536
