### ISSUE TITLE
The app's search box keep empty while searching

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1478]
**Describe the bug**
The app's search box keep empty while searching

**To Reproduce**
1. Go to Apps
2. Click on 'Search Apps'
3. Type some keywords to search, e.g. perplexity
4. The Search box keep empty

**Current behavior**
The Search box keep empty

**Expected behavior**
The search box show 'perplexity'

**Screenshots**

https://github.com/user-attachments/assets/9231bb78-fb36-4065-b465-09cdfb78931c

**Smartphone + device (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.5.1
 - App Version: 1.0.47
 - Device version: Omi DK2, firmware v2.0.7

**Comment by mdmohsin7** [comment]
This is strange, I tried locally just now and it works

**Comment by mdmohsin7** [comment]
Could not recreate on the latest testflight as well
