### ISSUE TITLE
Button doesn't work

### ISSUE THREAD

**Issue by huangxiangdan** [BasedHardware/omi#1491]
I followed [Omi Triangle v2](https://github.com/BasedHardware/omi/blob/main/Friend/hardware/triangle%20v2%20w%20memory/README.md) to build my Omi Triangle. Everything works fine, except button behavior. Nothing happened when I click or press and release the button.

When I build my own firmware, I found out something maybe wrong in [button.c](https://github.com/BasedHardware/omi/blob/main/Friend/firmware/firmware_v1.0/src/button.c#L58).

```
void` button_pressed_callback(const struct device *dev, struct gpio_callback *cb,

		    uint32_t pins)
{
   int temp = gpio_pin_get_raw(dev,d5_pin_input.pin); 
    printf("button_pressed_callback %d\n", temp);
    if (temp) 
    {
        was_pressed = false;
    }
    else 
    {
        was_pressed = true;
    }
}
```

When I reverse `was_pressed` value，the button works as excepted.

Please check it. Thx.

**Comment by beastoin** [comment]
man @huangxiangdan pls take a look into the `gpio_pin_get_raw` function to understand it then know how to use that function to detect the button pressed state. if you still see it is wrong, feel free to lmk.

**Comment by huangxiangdan** [comment]
@beastoin yeah, I checked the `gpio_pin_get_raw ` function, it returns
```
1	If pin physical level is high.
0	If pin physical level is low.
```
when the button pressed, the circuit is in on，so the d5_pin physical level should be high.

So I was very confused, When I saw
```
void button_pressed_callback(const struct device *dev, struct gpio_callback *cb,
		    uint32_t pins)
{
    int temp = gpio_pin_get_raw(dev,d5_pin_input.pin);
    printf("button_pressed_callback %d\n", temp);
    if (temp) 
    {
        was_pressed = false;
    }
    else 
    {
        was_pressed = true;
    }
}

```
And I run button test, without change anything, except comment two lines.
```
if (event == BUTTON_EVENT_SINGLE_TAP)
    {
        printk("single tap detected\n");
        btn_last_event = event;
        notify_tap();

        // Enter the low power mode
        is_off = true;
        // bt_off();
        // turnoff_all();
    }
```
Here is the result
```
 omi git:(main) ✗ python Friend/firmware/testing/button_test_files/button_test.py
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')  //click once
bytearray(b'\x03\x00\x00\x00\x00\x00\x00\x00')
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')  //double click
bytearray(b'\x03\x00\x00\x00\x00\x00\x00\x00')
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')  //long press
bytearray(b'\x03\x00\x00\x00\x00\x00\x00\x00')
```
That means button didn't show the correct state.

And when I reverse the `was_pressed` value
```
void button_pressed_callback(const struct device *dev, struct gpio_callback *cb,
        uint32_t pins)
{
    int temp = gpio_pin_get_raw(dev,d5_pin_input.pin);
    printf("button_pressed_callback %d\n", temp);
    if (temp) 
    {
        was_pressed = true;
    }
    else 
    {
        was_pressed = false;
    }
}
```
and run the test again.
```
python Friend/firmware/testing/button_test_files/button_test.py
bytearray(b'\x01\x00\x00\x00\x00\x00\x00\x00')   //click once
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')
bytearray(b'\x02\x00\x00\x00\x00\x00\x00\x00')  //double click
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')
bytearray(b'\x03\x00\x00\x00\x00\x00\x00\x00')  //long press
bytearray(b'\x05\x00\x00\x00\x00\x00\x00\x00')
```
It works as expected.

I'm lacking in hardware experience, I think something wrong, but I can't figure out why. Maybe I used wrong button, or something like that. If you know something, please let me know. I would be very grateful.
