### ISSUE TITLE
Omi AI app submission with the marketplace

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1540]
✅ WE need to provide a demo test email for apple in submissions like demo@apple.com, and in this email the  app marketplace SHOULD be disabled (or at least paid apps should be hidden)
✅ we can NEVER mention apps payments functionality to apple/google in "what's New" notes - if they see it they will trigger
✅ @thinh you need to remove $30/per month and replace it with "subscribe" 
ℹ️ when the person clicks on the button, you need to redirect them to a webview/site to actually subscribe
We need to add over-the-air updates as soon as possible so that Apple doesn't trigger
-> currently navigate to stripe link

ref: https://discord.com/channels/1192313062041067520/1295877183587221646/1316171505293332490

**Comment by beastoin** [comment]
@mdmohsin7 
>WE need to provide a demo test email for apple in submissions like [demo@apple.com](mailto:demo@apple.com), and in this email the app marketplace SHOULD be disabled (or at least paid apps should be hidden)

for this one.

**Comment by mdmohsin7** [comment]
Accounts created @beastoin

**Comment by beastoin** [comment]
@mdmohsin7 for the submit app logic, pls 1/ rquest the api /v1/app/plans with auth then 2/ check if having at least 1 plan then show the app pricing logic, if empty -> hide it.

ref: https://github.com/BasedHardware/omi/pull/1542/files#diff-2909fc3590a2e91de52c71f77e268a2da5db3a9bc7d936ca349398096a4595eaR292

**Comment by beastoin** [comment]
backend dev deployment: https://github.com/BasedHardware/omi/actions/runs/12335907335
