### ISSUE TITLE
Make notifications smart ($2000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#232]
Core value of our product should be proactive notifications
We should make it very very simple for developers to build plugins that use notifications. 

Creating a plugin with notifications should be so simple as we currently use memory/chat plugins with prompts, so that devsd could create notifications-plugins in 10 minutes.

We need to do 2 things:
1. plugin infrastructure + instructions that allows devs create plugins with notifications in 10 minutes
2. plugin-showcase (let's call it "mentor") that does these things below (they are sorted by importance):

ALL NOTIFICATIONS SHOULD BE BASED ON FACTS THAT APP KNOWS ABOUT THE USER

| What | Example |
|------|---------|
| During the meeting, I want to get advice to move faster either proactively or if I ask "hey Omi, what do you think?" | noticed you are trying to brainstorm ways of how to get viral on hackernews<br>If I were you, I'd publish your link first and then text Alex, James, Jacob and Scott and ask them to upvote. Just make sure not to send them direct links! |
| during and After the arguing, I want to get alternative opinion to know if i was wrong or another person.  (It should be triggered either when conversation ends (if there was an argument), or if I ask a codeword like "hey Omi, what do you think") | Hey Nik, you were talking with Joan about current goals. In my opinion, I think you should keep doing marketing activities because they bring you a lot of momentum, but also spend at least 40% on trying to make the product better. It's important to spend time on the product as well, since you don't yet have a product market fit and it's important |
| I want to get relevant questions during conversation that will help to extract more value from conversation | It seems Richard is very experienced in scaling hardware companies but you didn't ask him about it, even though it's your current main goal!<br>Ask him "how did you get your first 10k sales?" - this might help you with your goals |
| After meeting, I want to know how efficient was my communication | Nice work on that pitch, Joan! You've shown real improvement since last week. Let's go over the specific areas where you've gotten better.<br>In your last pitch, you got straight to the point without much of a warming-up period. This can sometimes feel cut and dry. Today, however, you took some time to engage with Leo, asked about him and the firm before diving into the subject matter. This created a more receptive environment for your pitch, which is a definite improvement. |
| I want to know what should I be working on this day, week and month | "Good morning! You mentioned that your weekly goals are "to get 10k users". Here is what I think you should be working on today<br>* Reach out to 3 influencers (your advisor Monisha recommended this earlier this week)<br>* Make the twitter announcement (this is what brings you most traffic)<br>* 20 SEO-optimized pages (in your last company SEO brought you biggest result)<br>Same for monthly and weekly |

But notifications should bring valuable feedback. Example of NOT VALUABLE feedbackl:
![Image](https://github.com/BasedHardware/Friend/assets/43514161/5c90a3ba-4d63-4207-a75c-51ec2f840a28)

As a user, I don't want useless notifications (like from above) to interrupt my day. I want to receive them rarely, but only when it's actually super important

**Comment by kodjima33** [comment]
Added +$500

**Comment by sophiahhuang** [comment]
Does that mean it's $1500 total?

**Comment by beastoin** [comment]
@mdmohsin7 after finishing the "renaming ticket, I need a dead-simple mvp version of this ticket (as we discussed). please take your time and happy coding 💪

**Comment by beastoin** [comment]
duplicated #1132
