### ISSUE TITLE
Onboarding improvement to learn more about users

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#316]
**Is your feature request related to a problem? Please describe.**
Problem, lack of segmentation for understanding users and taking better product decisions.

**Describe the solution you'd like**
There's a setup questions page right now, but it should be not on onboarding, but rather it should feel natural, and not like invasive to the user.

**Describe alternatives you've considered**
We could find a way to put it in the onboarding flow.

**Comment by bbookman** [comment]
this is fantastic.  user profiles would really help development and product management.  However, this only works if a resource is required to analyze this information (Applying AI!)

**Comment by bbookman** [comment]
Not sure if i should file this "add on" - the information provided by the user could be folded into memories in terms of biasing what is important to the user due to the profile.  This could apply to chat as well.  a bias to the user profile.  LMK if that is a separate feature request

**Comment by bbookman** [comment]
IMO P3

**Comment by josancamon19** [comment]
Maybe implemented
