### ISSUE TITLE
Create Contribution Guidelines

### ISSUE THREAD

**Issue by raymondyegon** [BasedHardware/omi#329]
**Is your feature request related to a problem? Please describe.**
For now we don't have any contribution guidelines. With contribution guidelines, it can help us have a more standard way of contribution and will also offer better support for new contributors.

**Describe the solution you'd like**

- Reporting Issues: Add a detailed section on how to report issues, including what information to include and how to format the issue for clarity.
- Submitting Pull Requests: Provide a step-by-step guide on how to submit pull requests, including forking the repository, creating a new branch, making changes, and submitting a pull request.
- Code of Conduct: Include a section that outlines the expected behavior of contributors and maintainers.
- Review Process: Describe the process for code reviews, including what contributors can expect and how they can address feedback.
- Discussion Participation: Encourage participation in discussions and provide guidelines on how to engage respectfully and constructively.
- Formatting guide: Set rules for a uniform standard formatting.
- Commit Guide: Have a standard way of how commits are written

**Additional context**
I encourage everyone to actively participate in shaping this document.

**Comment by raymondyegon** [comment]
@josancamon19 Kindly assign me this task. 

cc @kodjima33

**Comment by bbookman** [comment]
IMO P1

**Comment by josancamon19** [comment]
Done already.
