### ISSUE TITLE
Allow private plugins

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/omi#330]
User might desire plugin-type processing that is hyper-specific and not much help to the community.  Implement a mechanism for user to create plug-ins that are private

https://discord.com/channels/1192313062041067520/1246638931857113150/1250991753524281426

**Comment by nathansudo** [comment]
I love this idea, it would be helpful to test some ideas before you make them public as well -- similar to GPTs in ChatGPT where you can make your own but then share them with the community as well.
