### ISSUE TITLE
Integrate Shorebird for Over The Air Updates 

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/Omi#365]
**Is your feature request related to a problem? Please describe.**
Currently Play Store does not allow rolling back updates, which means in case of critical bugs we will have to publish a new release and will have to wait until Google approves it (it can take around upto 10-12 hours)

**Describe the solution you'd like**
Integrating Shorebird, which provides Over the Air update functionality, we can push fixes to critical bugs without having to rely on Play Store. It is very similar to Code Push for React Native

**Describe alternatives you've considered**
There aren't any alternatives, Shorebird is created by the creator of Flutter itself

**Additional context**
https://shorebird.dev/

**Comment by Becca-Saka** [comment]
Hi @josancamon19, Already working on this, please assign me to this task.

**Comment by mdmohsin7** [comment]
Nothing against anyone, but in my opinion, @josancamon19 himself should integrate Shorebird. The integration process only involves creating an account and setting the app IDs in Shorebird, which is done automatically. Even after @Becca-Saka integrates it, Joan will have to follow all the steps again. If Joan shares the credentials for the Based Hardware account with Rebecca, then the setup won't need to be repeated.

**Comment by Becca-Saka** [comment]
Yeah, I get you, I had reached out to @josancamon19 earlier on discord on how we should go about that.

**Comment by josancamon19** [comment]
Done
