### ISSUE TITLE
Include onboard memory storage ($700 USD)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#376]
**Is your feature request related to a problem? Please describe.**
Include onboard memory storage so that the user by just having the device on his neck, never loses a single audio byte of information.

**Describe the solution you'd like**

- This should include hardware update, and instructions, on how to solder/add the memory component + details on the component.
- This should include firmware update, so that the audio bytes are sent and stored and if not received, it should remove the bytes from the memory.
- This should include a functionality when the app connects again, it should send whatever bytes are in the storage to be processed in the app, once the processing happens, it should clean the audio bytes from storage.

This solution includes hardware, firmware, and flutter.

**Comment by Gashpid** [comment]
Hey, I’m gonna take this feature.

**Comment by josancamon19** [comment]
Assigned to Gashpid

**Comment by Gashpid** [comment]
I attach the preliminary README file and a couple of images for such README. I'm attentive to any suggestions or changes required.

[README.md](https://github.com/user-attachments/files/16038744/README.md)

![local_storage_diagram](https://github.com/BasedHardware/Friend/assets/18086290/5daecec1-1c29-451e-a0b0-b9829ad885df)

![local_storage_connection_diagram](https://github.com/BasedHardware/Friend/assets/18086290/b0d92d2f-7810-4aaa-b483-f25bf46db288)

**Comment by josancamon19** [comment]
# Redundant local storage

<div align="center">
    <img src="local_storage_diagram.png" alt="#">
</div>
<br/>

<div style="text-align: justify;">
This solution integrates a microSD memory to provide redundant storage on the device. The redundant storage ensures that the audio files are temporarily saved on the microSD until it is confirmed that they have been correctly transferred to the mobile application. Once the transfer is validated, the data stored on the microSD is deleted, thus ensuring efficient and secure information management. This feature uses a microSD module that operates via SPI, functioning as a bridge between the “XIAO-nRF52840 Sense” board and the micro-SD memory. A notification service is also added to the mobile application to alert if the delayed data has arrived correctly.
</>

## MicroSD Card Module Pin Configuration - SPI

<div align="center">
    <img src="local_storage_connection_diagram.png" alt="Texto alternativo de la segunda imagen">
</div>

The micro-SD card module communicates via the SPI communication protocol. You can connect it to the XIAO-nRF52840 Sense using the default SPI pins. You can buy this module in [Amazon](https://www.amazon.com/RedTagCanada-Storage-Expansion-Soldered-Arduino/dp/B09LTMLJ12/ref=sr_1_61?crid=186EM4TGBRTT&dib=eyJ2IjoiMSJ9.ysWkCOQcBTdneiBpSvvAKKrtj7srmVoT71imrzeFa0enSmZvw0bG4MnVgIHU80dJ1zWteuQVzG4TlX2TxajJ8cVh79vZ1S1Eu3v5B0XQIuI-qvzZg566tzu60kRMY-mrgCmq7vkAS5yNwVG-lAFufuAdS2GNjGKbPUImbbQkh58zZ5YdNiGHNQXyScVS9l3o.81e3AigkNOWHioavXqN1PWDc-NdvahtwwMaEmpgkarc&dib_tag=se&keywords=micro%2Bsd%2Bcard%2Bbreakout&qid=1719634567&sprefix=micro%2Bsd%2Bcard%2Bbre%2Caps%2C210&sr=8-61&th=1)

|  Pin  | SD Card Module | XIAO-nRF52840 |
|-------|----------------|---------------|
|   1   |      3V3       |     VDD       |
|   2   |      CS        |     P1.12     |
|   3   |      MOSI      |     P1.15     |
|   4   |      CLK       |     P1.13     |
|   5   |      MISO      |     P1.14     |
|   6   |      GND       |     GND       |
 
## Preparing the microSD Card

Para  hay que asegurarse que la tarjeta microSD tenga el formato FAT32. Puedes usar el software [SD Card Formatter](https://www.sdcard.org/downloads/formatter/) (compatible con Windows y Mac OS).

**Comment by przemeks13** [comment]
I can do the CR if the MR is ready. I'm interested in this featrue as well :)

**Comment by kodjima33** [comment]
Testing the Friend Dev Kit 2 with onboard memory
https://x.com/kodjima33/status/1821324066651041837?s=46

Before mass-shipping, It Needs this task completed 

If you want to work on firmware, buy the device here and we will refund you if you push any code https://basedhardware.com/products/friend-dev-kit-2

**Comment by theadrianm** [comment]
Hello! I can push code - software developer with over 3 years of experience. Assign me a task, I'll purchase the device and when I push it just get the refund

**Comment by josancamon19** [comment]
Moving this to #570
