### ISSUE TITLE
Build audio player functionality on memory detail ($400)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#381]
**Is your feature request related to a problem? Please describe.**

I want to be able to play the audio recordings on the app, with the same functionality as shown on the video, with a very similar UI but matching our styles.

- Play pause buttons
- +15 -15 seconds increments
- Playback speed options
- Wave component based on audio with current second playing line that drags and drop to the second.

https://github.com/BasedHardware/Friend/assets/18078879/bf9609c9-c437-4da2-bc91-bd5f09eabe2e

https://github.com/BasedHardware/Friend/assets/18078879/48f446a7-5103-4b5e-9f74-5c70eb127c31

**Describe the solution you'd like**
Make sure `memories.dart` `Future<Memory> finalizeMemoryRecord(` stores the recordingAudioPath as it should.
Implement the feature explained above.
Handle edge cases where the audio file is not found.
Make sure app lifecycle states are managed, and that audios don't keep playing when they don't have to.
UI should be very similar / same, with our colors.

**Note:**

In case the audio file is a hosted URL from like google cloud, this should still work. Check storage.dart.
There should be an option in settings to remove all audio files data stored locally, like cleaning, with a confirmation action, in case the app is occupying too much for this files, it should show the amount of Gb is occupying.

**Comment by SHAH-JI** [comment]
to @josancamon19 
You require an Audio Player only, Transcript and Summary are not included, right?

**Comment by SHAH-JI** [comment]
to @josancamon19 
Can you please assign this to me?

**Comment by josancamon19** [comment]
@SHAH-JI correct, is the audio player, with the exact same functionality as shown in the video.

**Comment by Washyl** [comment]
to @josancamon19 
Can you please assign this to me?

**Comment by SHAH-JI** [comment]
to @josancamon19 
For the AudioPlayer, here is a initial implementation with sample audio files. Please check and let me know if there are any changes to be made.
PR: https://github.com/BasedHardware/Friend/pull/399

**Comment by josancamon19** [comment]
Implementation was terrible, so closing this issue for now. Will re open later

**Comment by Abhisheksainii** [comment]
@josancamon19 I would like to work on this feature. Can it be assigned?

**Comment by Agrim2112** [comment]
@josancamon19 I would like to implement this feature, can this be assigned to me?

**Comment by josancamon19** [comment]
Maybe will reopen in the future.
