### ISSUE TITLE
[DRAFT] Summaries are generated in markdown

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#391]
**Is your feature request related to a problem? Please describe.**
In this format, everything can be edited, and the summary could contain any possible parsing prompt, without worrying about 3 specific fields, or the user could use custom prompts.

- Make sure database remain with those fields, but become optional.
- Use Langchain MarkdownOutputParser for parsing instructions.
- New database field with summary: str ~ markdown result.
- Handle memory detail UI so previous memory with current structure are shown as they are, but new ones with summary too.
- Reprocess memory option, sets markdown for previous memories too, in case the user wants to migrate some memories to new format.

**Comment by beastoin** [comment]
duplicated #1216
