### ISSUE TITLE
Store raw audio recordings

### ISSUE THREAD

**Issue by ErikBjare** [BasedHardware/omi#433]
### Is your feature request related to a problem? Please describe.

Transcription/diarization isn't perfect. Many analysis methods require raw audio.

It'd be great if we could choose (opt-in) to store raw recordings, in order to allow for post-hoc:
 - transcription
 - diarization, learning speakers
 - sentiment analysis
 - removing/measuring background noise
 - training models
 - playback of past conversations

### Describe the solution you'd like

I'd like an option in the settings where the users can choose to store raw recordings locally. Preferably stored directly in a folder (so that the user can choose to sync it with e.g. Syncthing), or in app storage with option to export.

If this is considered too much of a "power user" feature, it could be stashed away in the developer settings.

I'd be happy to contribute this feature, I just need to get acquainted with Flutter first.

Edit: I went through the code and found [`Memory.recordingFilePath`](https://github.com/BasedHardware/Friend/blob/24411a469b589e1e96f80ec41b2fd44682bc7365/apps/AppWithWearable/lib/backend/database/memory.dart#L25). Perhaps this simply be exposed to the user? Although its limited occurrences in the codebase seems to suggest it's unused?

### Describe alternatives you've considered

 - [x] ~~Building my own app for always-on recording~~
   - I basically abandoned this idea when Rewind.ai appeared. Then considered building it again, after being somewhat disappointed by certain hacker-unfriendly decisions at Rewind.ai. Then no longer considered it after seeing Friend :)
   - I previously used a plain voice recorder app for a long time, but it's annoying that it's not "always-on" and that I have to manually transcribe/analyze.
 - [x] Investing in competitors
   - https://rewind.ai, semi-pivoted to https://limitless.ai
     - Seem to be moving in a "no raw audio" direction with the Limitless app & wearable, disappointingly.
 - Forking the Friend app (if all else fails)

### Additional context

I've long thought about the general problem of tracking your context ([ActivityWatch](https://github.com/ActivityWatch/activitywatch) and related work). During development, I realized that it was important to store data as it was observed, and leave aggregation/analysis to a later step to avoid information loss. We outlined this very early on as the core tenet of our "[Data philosophy](https://docs.activitywatch.net/en/latest/introduction.html#data-philosophy)". I'd humbly suggest Friend considers a similar approach.

**Comment by josancamon19** [comment]
Hi @ErikBjare latest app version can store the recordings, unfortunately we can't allow users to check them later.
If you host your own backend, you wouldn't need to modify the code or anything, just to deploy it.

**Comment by ErikBjare** [comment]
@josancamon19 Thanks, I'll have a look :)
