### ISSUE TITLE
Send raw audio file to a custom server

### ISSUE THREAD

**Issue by eladrave** [BasedHardware/omi#478]
**Is your feature request related to a problem? Please describe.**
Currently, I can't access ALL the raw file data. Sometimes it works and I can find the data on GCP, but it's very random, and I don't know if it will be saved, and what will be saved.
Also, 
Due to Deepgram implementation - it doesn't support languages other than English

**Describe the solution you'd like**
For every recording, the audio will be sent to a URL that I can define on the app.

**Describe alternatives you've considered**
the GCP integration, which doesn't work all the time

**Additional context**
Would put a bounty amount on this

**Comment by AnkushMalaker** [comment]
Can you write a quick note about why above PR was closed? @josancamon19 
Thanks!

**Comment by josancamon19** [comment]
PR's of VirtualHorror were LLM automated and non sense.

**Comment by josancamon19** [comment]
Also, latest backend is already doing this @eladrave you can check it out hosting your own backend. Sending the file somewhere else will not be implemented for now.
