### ISSUE TITLE
DoorDash plugin ($500)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#488]
Need a plugin so that you could order DoorDash if you mention "I want *** food from doordash"

**Comment by kevvz** [comment]
Can I be assigned this?

**Comment by maishathasin** [comment]
Hi @kodjima33  and @josancamon19  I can take this , please assign me this issue!

**Comment by josancamon19** [comment]
Assigning to @maishathasin for the next 2 days.

**Comment by merouanezouaid** [comment]
i'm taking this one :)

**Comment by josancamon19** [comment]
Closing, not planned for now, will reopen later probably.
