### ISSUE TITLE
Do not ask for permission again when it's refused

### ISSUE THREAD

**Issue by jzarca01** [BasedHardware/Omi#492]
**Describe the bug**
On iOS, I declined location, then every time I start the app, I'm redirected instantly to settings, then when I switch to Friend I get that modal asking for location again. Even after changing location permissions to Always I keep getting the same issue.

**To Reproduce**
1. Open Settings
2. Change Friend location permission to Never
3. Open Friend
4. See user being redirected to Settings
5. Go back to Friend
6. Wait for modal to appear
7. Click on Confirm
8. Change Friend location permission to anything else
9. Restart Friend
10. See error

**Expected behavior**
If permission is refused the first time, no modal should appear the next time user opens the app, no redirection either.

**Screenshots**
https://github.com/user-attachments/assets/31269980-2bb7-4c7a-92d9-2e72fe671c4a

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17
 - Version 1.0.19

**Comment by josancamon19** [comment]
I think this should be fixed already! please lmk if not.
