### ISSUE TITLE
Build a Plugin example using the memory created audio ($250)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#493]
**Is your feature request related to a problem? Please describe.**
Example: sentiment analysis from the audio using Hume API. This can't be done with only the transcript. check recordingBase64 param in the webhook.

**Describe the solution you'd like**
A plugin that provides Hume API insights from conversations, like speakers feelings, etc, and gives a notification when something was odd, or not ideal.

**Comment by ebowwa** [comment]
please assign me

**Comment by ebowwa** [comment]
hey there, 

progress update: 
- modified the backend to output a storage bucket url for the audio file to make accessible via third-party services

next steps:
- build the flutter app to test the backend changes and upload a plugin to demo 

[Forked Repo](https://github.com/ebowwa/Omi)

**Comment by josancamon19** [comment]
Canceling, already built on post-processing memory endpoint. No as plugin.
