### ISSUE TITLE
Google Drive Export Plugin ($400)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#494]
**Is your feature request related to a problem? Please describe.**
Users have a plugin where they can enable google drive, so their memories are stored there, this has an option to select what parts of it, like transcript, raw audio, and others.

This requires hosting your own settings website, where users configure this preferences.
a query parameter `?uid=` is sent to all the links you put on the readme page.

Check this notion example: https://github.com/BasedHardware/Friend/blob/main/plugins/example/basic_auth/memory_created.py

Users should have a list of checkboxes of what things from the memory they wish to store in google drive, and they should be able to set the folder where all of it will be stored.

**Comment by anshulkr04** [comment]
i think i might be able to do this . Can you assign me ??

**Comment by josancamon19** [comment]
Assigning to @anshulkr04 for the next 2 days

**Comment by alt-P-git** [comment]
@josancamon19 I would like to work on this issue. Can I be assigned ?

**Comment by josancamon19** [comment]
Hi @alt-P-git lmk if you are still interested.

**Comment by alt-P-git** [comment]
Yes, I am interested but it is unclear to me what do you mean by the website for hosting the settings, and the link leads to 404

**Comment by rkjain119** [comment]
Hello @josancamon19 can you assign this to me i can do this

**Comment by josancamon19** [comment]
Sure @rkjain119 assigning for the next 2 days, please create a Draft PR when you get started so we can see progress.

**Comment by smian1** [comment]
@josancamon19 Assign it to me and mark it complete.

**Comment by smian1** [comment]
@kodjima33 assign and close. This one is done too.
