### ISSUE TITLE
updating Boot loader to 0.9.0 and FW to  v1.0.3-firmware no capturing

### ISSUE THREAD

**Issue by darklite80** [BasedHardware/Omi#497]
i was having stability issues(lost internet not transcribing as it was before) after the ios App update last week around 25Jul24 (i updated bootloader (0.9.0) and firmware(v1.0.3)  yesterday flashing was sucessful but on [v1.0.3-firmware] status led blinks red app shows listening and connected but no capturing is happening.app shows friend fw is 1.0.2. tried to flash the more recent 1.0.4 and friend status led shows blue and same result of friend app showing current friend firmwarre is 1.0.2 and no captutre

I am using kickstarter hardware,

**Comment by josancamon19** [comment]
Fixed, on 1.0.4
