### ISSUE TITLE
Setup One Signal notifications from backend, or remote notifications with firebase so we can trigger the daily summary from backend ($250)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#503]
**Is your feature request related to a problem? Please describe.**
We need to collect the user firebase token for notifications (if firebase route, store it somewhere)
And create a cronjob, that at 8pm user's time, triggers a notification everyday with their summary.
This notification data, should be added as a message to the app locally (but should be added in the backend aswell to the messages collection)

**Comment by josancamon19** [comment]
**Extra detail:** A new thread should be started, so that it calls utils.plugins.trigger_realtime_integrations + the app receives the notification message + get's added to the app.
![CleanShot 2024-08-04 at 23 40 26@2x](https://github.com/user-attachments/assets/9b51fc7a-4e26-48b5-af0b-44cd3cf3bd27)


This would restore realtime plugins.

**Comment by Androidsignal** [comment]
I can implement using the Firebase function (.js). can you assign me this task @josancamon19

**Comment by josancamon19** [comment]
Assigned to @Becca-Saka already

**Comment by Becca-Saka** [comment]
Hi @josancamon19, Please assign this to me.

**Comment by josancamon19** [comment]
Already in main, fixed by @Becca-Saka
