### ISSUE TITLE
Google Calendar Plugin (External Integration) (On Memory Created) ($300)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#508]
**Is your feature request related to a problem? Please describe.**
I want a plugin that let's you connect your friend account as an external integration.

You should create it in plugins/example/google_calendar folder as a router.

The oauth should be managed by the plugin.

When a memory creates, that should receive the memory object and create a calendar event.

If created should notify back the user in the message field.

**Comment by Tresor-Kasenda** [comment]
Hey there I hope you are doing well I would know how to contribute to this issue

**Comment by josancamon19** [comment]
Assigning to @Tresor-Kasenda for the next 2 days

**Comment by anshulkr04** [comment]
i already raised a pull request

**Comment by josancamon19** [comment]
Thanks @anshulkr04 
But this was assigned to @Tresor-Kasenda 

If it's assigned to someone that person is working on it, and will get the bounty once they complete it.
If for some reason the asginee doesn't deliver the task, then we will consider your PR.

**Comment by josancamon19** [comment]
Hi @Tresor-Kasenda looking forward for a Draft PR today, if not, ticket will be assigned to @anshulkr04

**Comment by invarrow** [comment]
@josancamon19 the issue has been pending for a while
I can get it done and a draft a PR if assigned...

**Comment by smian1** [comment]
@josancamon19 @kodjima33 assign to me and close please. It's done :)
