### ISSUE TITLE
Finish notion integration plugin ($200)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#509]
**Is your feature request related to a problem? Please describe.**
https://github.com/BasedHardware/Friend/blob/main/plugins/example/basic_auth/memory_created.py

The notion memory created plugin is super rusty and could be much better.

**Describe the solution you'd like**
The setup form + on completed page should be beautiful, and have some sort of Friend <> Notion Integration UI.

`create_notion_row` should validate the user created the proper table, and if not, return a message accordingly.

Instead of the user having to setup their own integration, this should be a notion oAuth page, so you need to create a notion application, and allow oauth.

The oauth is done from the links you put in the README.

(This should be in another folder inside example/oauth) ~ but the community-plugins.json file should be updated to point to this new endpoint.

**Comment by beastoin** [comment]
## Thinh's change logs
1. Notion OAuth is now ready

  - Demo: https://github.com/user-attachments/assets/0f1e0794-86ae-4282-a140-68222193ad2f
  
2. What/s next?

   - ✅ Notion OAuth
   - ☑️ Validate for create_notion_row function.
   - ☑️ Dir example/oauth, communition-plugins.json

A PR will be sent after all tasks are done, or this task needs to be split into smaller parts.

Good day ~

**Comment by beastoin** [comment]
## Thinh's change logs
1. Done for the rests, please take a look at PR https://github.com/BasedHardware/Friend/pull/551
  
2. What/s next?

   - ✅ Notion OAuth
   - ✅ Validate for create_notion_row function.
   - ✅ Dir example/oauth, communition-plugins.json
   - ☑️ Fix review / feedback

Good day ~

**Comment by josancamon19** [comment]
Will review the PR and give feedback soon!

**Comment by beastoin** [comment]
Thank you @josancamon19

**Comment by beastoin** [comment]
## Thinh's change logs
1. PR merged https://github.com/BasedHardware/Friend/pull/551
  
2. What/s next?

   - ✅ Notion OAuth
   - ✅ Validate for create_notion_row function.
   - ✅ Dir example/oauth, communition-plugins.json
   - ✅ Fix review / feedback

Cheers !!!

**Comment by beastoin** [comment]
Thanks!

![image](https://github.com/user-attachments/assets/60119fba-4984-482a-99a0-e1488a65a1d5)
