### ISSUE TITLE
Integrate Screen Pipe <> Friend

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#514]
**Is your feature request related to a problem? Please describe.**
Screen pipe desktop app should be able to populate friend app memories, from your desktop data.

**Describe the solution you'd like**
To connect Screen pipe with friend, so that people can use the desktop app to collect their memories from computer.

https://screenpi.pe/
https://github.com/louis030195/screen-pipe

**Comment by m13v** [comment]
Matthew Diakonov here

**Comment by m13v** [comment]
I'll deploy plugin with easy instructions to set it up

**Comment by m13v** [comment]
Hey @josancamon19, would you like to test the plugin before it's publicly available? It's ready

**Comment by josancamon19** [comment]
Implementation was not completed, removing ticket.
