### ISSUE TITLE
Backend Websocket in modal has a lot of disconnect bugs reports

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#515]
**Is your feature request related to a problem? Please describe.**
When you deploy the backend to modal, we get a lot of errors as if the Websocket had a lot of issues, but what's happening is a disconnect error, this is mainly a backend task, to make sure the disconnection is handled properly, and the errors in modal are not triggered.

When this is fixed, we should be able to handle gracefully app Websocket disconnections.

![CleanShot 2024-08-02 at 18 23 55@2x](https://github.com/user-attachments/assets/c799a907-94ae-4527-a872-0aa02a0a0757)
![CleanShot 2024-08-02 at 18 24 03@2x](https://github.com/user-attachments/assets/4043730d-f663-4764-bf9a-ab7895ca8493)
![CleanShot 2024-08-02 at 18 24 18@2x](https://github.com/user-attachments/assets/04c85cdb-a042-4366-adb5-e68d7ea40e96)
![CleanShot 2024-08-02 at 18 24 26@2x](https://github.com/user-attachments/assets/2a5fd7be-197a-4493-9326-c81e2fbc9e5a)

**Comment by D1ll4nT** [comment]
I committed some code that should improve the stability. I don't have the credentials thought so I can't test it. Do you mind testing it to see if it performs better?

**Comment by josancamon19** [comment]
Hey, @D1ll4nT happy to review, pls change your PR to Draft PR, and please deploy the backend to your own modal, it should be easier to test that way.

**Comment by josancamon19** [comment]
Assigning to you for the next 2 days @D1ll4nT
