### ISSUE TITLE
Instabug becomes error free!

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#516]
**Is your feature request related to a problem? Please describe.**
There are many unneeded errors in instabug, that need to be handled better from the app.
![CleanShot 2024-08-02 at 18 26 24@2x](https://github.com/user-attachments/assets/ff3b4cf2-b7a9-4328-8d0e-04f757b4ad17)
![CleanShot 2024-08-02 at 18 26 36@2x](https://github.com/user-attachments/assets/6b48167b-6229-4ad4-b8ba-e99d8eec8f70)

**Describe the solution you'd like**
This errors should be fixed in the app.
+ Should stop appearing in instabug.

https://dashboard.instabug.com/crashes/OrG6FlUU7LSuSoOGIj4jbA

https://dashboard.instabug.com/crashes/OrG6FlUU7LSuSoOGIj4jbA

**Comment by Wolfof420Street** [comment]
can I get more context on this @josancamon19 ?

**Comment by Wolfof420Street** [comment]
I'd like this assigned to me @josancamon19

**Comment by josancamon19** [comment]
This task would also include crashes and bugs section in Instabug, to make sure user reported bugs get solved.
If this tasks requires complex backend changes like transcript websocket, or something related to speech profile, I would be able to help there, still, 95% of issues should be flutter based changes.

**Comment by josancamon19** [comment]
@Becca-Saka
