### ISSUE TITLE
Chat RAG can use tool functions and has better performance. ($300)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#526]
**Describe the feature**
Current chat is a 2 prompts,
1. determines context
2. qaRag prompt

Check `backend/utils/llm.py`

Chat should be a langchain agent instead, that has a retrieval function with multiple options.
Topics, date based, individual memories..

I want to have a much better chat performance. ~ performance refers to capabilities of the chat retrieval.
Additionally, I want to be able to chat with individual memories.

This might include better vectorization of current memories structure.

(This might include a better vectorization of the current memories)

**Comment by aialok** [comment]
Hey, I would lovw to work on this issue.
I have experience with RAG, VectorDB and langchaun things.

Please assign me this issue : )

Thank you !!
Happy coding : )

**Comment by aialok** [comment]
Hey, I would love to work on this issue.
I have experience with RAG, VectorDB and langchain things.

Please assign me this issue : )

Also, I am building a RAG webapp for my college, ask anything about my college it will tell you. https://github.com/aialok/iiitr.insights

Thank you !!
Happy coding : )

**Comment by josancamon19** [comment]
@advaitpaliwal

**Comment by josancamon19** [comment]
Assigning to @aialok for the next 2 days 
Thank you for the help! happy to include a bounty to it :)

**Comment by aialok** [comment]
Thanks @josancamon19.
I don't find any documentation for setting up the backend. It would be great if there were some.

```
HUGGINGFACE_TOKEN=
BUCKET_SPEECH_PROFILES=
BUCKET_BACKUPS=
GOOGLE_APPLICATION_CREDENTIALS=google-credentials.json

PINECONE_API_KEY=
PINECONE_INDEX_NAME=

REDIS_DB_HOST=localhost
REDIS_DB_PORT=6379
REDIS_DB_PASSWORD=


SONIOX_API_KEY=
DEEPGRAM_API_KEY=

ADMIN_KEY=
OPENAI_API_KEY=
```

I'm currently encountering an error while setting up the environment, and I have a few questions before I proceed:

- What should the google-credentials.json file contain?
- What is the purpose of the ADMIN_KEY? Do I need it to set up the project locally?
- Do both BUCKET_SPEECH_PROFILES and BUCKET_BACKUPS need to be configured to run the project locally?

I think there should be proper documentation for setting up the backend. For example, new contributors don't have an idea of what the appropriate dimensions for our model for vector embedding would be.

![image](https://github.com/user-attachments/assets/8145e7f5-7246-4bb2-8fa3-e6feb408e017)


Edit : 

Thanks ! I have resolved all the issue : )

**Comment by aialok** [comment]
@josancamon19 need some time. 
As last week of my GSoC is going on need to wrap all the things.

Thank you : )

**Comment by reharsh** [comment]
hey @josancamon19, I am quite familiar with RAG/langchain, I am starting to work on this can you please assign this issue to me

**Comment by aialok** [comment]
Hey @josancamon19 ! I will work on this issue as I discuss with you already I am done with some work. 
my GSoC is about to end in week then I will make a PR for sure.

**Comment by josancamon19** [comment]
https://discord.com/channels/1192313062041067520/1252164267688591360/1276974348871270493
