### ISSUE TITLE
Plugin for users to be able create Zapier integrations when a memory created. ($1500) 

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Omi#535]
**Is your feature request related to a problem? Please describe.**
Users want to be able to connect Zapier with their Friend app. Users want a trigger "on memory creation" and action "create memory in Friend App"

**Describe the solution you'd like**
You need to make a "Zapier" plugin for Friend app, in which the user will be able to authorize Zapier app and connect Friend app to other apps
Along with that you need to submit the integration into Zapier marketplace. You can ping me or @josancamon19 once you have the code for integration ready

You need code for 2 features: 

- Trigger on memory creation (should work as a trigger in Zapier once new memory is created).
Example: I am wearing friend and just finished a conversation => memory got created. I want to be able to put it into my notion table through zapier (so I need to have a trigger on memory creation) 
- Action (Create memory) - should work as an action in zapier so that users are able to create "memories" in friend app. Example: you created a new page in notion => it should automatically go to Friend's backend 

[Learn how to create plugins here](https://docs.basedhardware.com/developer/plugins/Introduction/)

**Describe alternatives you've considered**
Check example: https://zapier.com/apps/mem/integrations

**Additional context**
This is a paid task. Reward is $1250 in cash. Simply link your PR with this task and we will check it asap. Check how Contributions and bounties work [here](https://basedhardware.com/contribute)
If no one is assigned to this task, then no one is working on it. We don't lock bounty tasks unless you've created PRs before.

**Comment by jainpawan21** [comment]
@kodjima33 I have experience of working with Zapier APIs. Can you assign this task to me?

**Comment by taaha161** [comment]
@kodjima33 Can i be assigned this task?

**Comment by tylerbordeaux** [comment]
Currently working on this

**Comment by josancamon19** [comment]
Not assigning to @taaha161 as was already assigned a task in the past and never delivered.

**Comment by josancamon19** [comment]
Assigning to @jainpawan21 for the next 2 days.

**Comment by josancamon19** [comment]
This should be in the folder plugins/example

**Comment by taaha161** [comment]
@josancamon19 I never delivered before because the task is was working on got assigned to someone else in the middle of me doing it

**Comment by josancamon19** [comment]
Please check the contribution guide, I asked to create a PR or show progress while you get it assigned, I didn't see progress, that's why. Supper happy to try again, and assign you another task. @taaha161

**Comment by josancamon19** [comment]
@jainpawan21 no respond or update, unassigning task.

**Comment by beastoin** [comment]
Should I...🤔

**Comment by kodjima33** [comment]
hey @beastoin - feel free to go ahead and try building this. We won't be able to assign tasks with no prior submitted PRs

**Comment by beastoin** [comment]
Yes @kodjima33 . Drop your proposal first, show you can get the job done, assigns will come after - that is the way. Simple. Just waiting for my first PR be merged then I can move to the next.

**Comment by beastoin** [comment]
Proposal & First draft version for this task(and tasks related to Automated Workflow Platform) will be drop in next 8 hours. Stay tune.

Your Team is great! @kodjima33 / kudos @josancamon19 

P/S: My first PR just be merged.

**Comment by beastoin** [comment]
# Thinhs change logs
1. Proposal v1.0 is read:
[Thinhs_Proposal_Plugin_for_users_to_be_able_create_Zapier_integrations_when_a_memory_created._(1500)_535.pdf](https://github.com/user-attachments/files/16568988/Thinhs_Proposal_Plugin_for_users_to_be_able_create_Zapier_integrations_when_a_memory_created._.1500._535.pdf)

2. What's next?
  - ✅ Draft the proposal
  - ☑️ Waiting for feedback / assigns
  - ☑️ Implement (make it happen)

Good day!

**Comment by beastoin** [comment]
hi @josancamon19 please take a look (any time that works for you).

p/s: guys, who want to help on finish tasks related to Automation Platform likes Zapier, Make.com, feel free to use this proposal as a reference, take everything you want from this (likes my meme!), to kill your task fast, with high-quality.

**Comment by 0w9** [comment]
Hey, will work on this for the hackathon :)

**Comment by josancamon19** [comment]
Assigned to @beastoin

**Comment by beastoin** [comment]
# Thinhs change logs
1. Got the assignment, now we will focus on the implementation.
2. What's next?
  - ✅ Draft the proposal
  - ✅ Waiting for feedback / assigns
  - ☑️ Implement (make it happen)

Good day!

**Comment by beastoin** [comment]
# Thinhs change logs
1. Omi(Dev) Zapier App is live on the sandbox mode, auth ready.
  - <img width="533" alt="Screenshot 2024-08-11 at 15 45 07" src="https://github.com/user-attachments/assets/3c104896-b94d-4004-b74e-17704ed4e565">
  - <img width="588" alt="Screenshot 2024-08-11 at 15 45 11" src="https://github.com/user-attachments/assets/485449d4-14e6-40c0-b29a-fbc1483fa1d9">

2. Omi Zapier Plugin achieved 3 features: Friend App auth(user enable the plugin), Zapier auth(connect Zapier account and Friend), subscribe/unsubcribe webhook from Zapier.
 - <img width="607" alt="Screenshot 2024-08-11 at 15 46 18" src="https://github.com/user-attachments/assets/881a07e4-f73d-4877-9b1f-9ce455e2597a">

3. Architect updates with 3 flows: auth(green), trigger new memory created(red), action create memory(blue)
 . <img width="2223" alt="Screenshot 2024-08-11 at 15 47 27" src="https://github.com/user-attachments/assets/3507706a-372a-4b5e-ad4e-b3754a83d9f2">

4. What's next?
  - ✅ Draft the proposal
  - ✅ Waiting for feedback / assigns
  - ☑️ Implement (make it happen) (30%)
    - ✅ Create Zapier App for Friend
      - ✅ Create Friend Zapier App
      - ✅ Create Friend Zapier Plugin
      - ✅ Integrate with auth
    - ☑️ Create Trigger Friend’s memory created on Friend Zapier (1/2)
      - ✅ Subscribe / Unsubscribe
      - ☑️ Define output model and testing
    - ☑️ Create Action Save memory to Friend
    - ☑️ Publish Zapier App

Good day!

**Comment by beastoin** [comment]
# Thinhs change logs
1. Trigger New memory created is now ready. Means: You can choose Omi > New memory created trigger when creating new Zapier Zap, all sync with your Friend.

<img width="1445" alt="Screenshot 2024-08-12 at 04 54 31" src="https://github.com/user-attachments/assets/a26a8155-8028-47d4-aa6e-e9a3e7b0dc5a">
<img width="1312" alt="Screenshot 2024-08-12 at 04 55 59" src="https://github.com/user-attachments/assets/73ea977d-2a52-479f-8999-bd8eb54c1170">


2. What's next?
  - ✅ Draft the proposal
  - ✅ Waiting for feedback / assigns
  - ☑️ Implement (make it happen) (50%)
    - ✅ Create Zapier App for Friend
      - ✅ Create Friend Zapier App
      - ✅ Create Friend Zapier Plugin
      - ✅ Integrate with auth
    - ✅ Create Trigger Friend’s memory created on Friend Zapier
      - ✅ Subscribe / Unsubscribe
      - ✅ Define output model and testing
    - ☑️ Create Action Save memory to Friend
    - ☑️ Publish Zapier App

Good day!

**Comment by beastoin** [comment]
### Thinhs change logs
1. Action is now ready.
2. What's next?
  - ✅ Draft the proposal
  - ✅ Waiting for feedback / assigns
  - ☑️ Implement (make it happen) (70%)
    - ✅ Create Zapier App for Friend
      - ✅ Create Friend Zapier App
      - ✅ Create Friend Zapier Plugin
      - ✅ Integrate with auth
    - ✅ Create Trigger Friend’s memory created on Friend Zapier
      - ✅ Subscribe / Unsubscribe
      - ✅ Define output model and testing
    - ✅ Create Action Save memory to Friend
    - ☑️ Publish Zapier App
      - ☑️ Feature feedback
      - ☑️ Code review
      - ☑️ Deploy @ Submit to Zapier

Good day!

**Comment by josancamon19** [comment]
Hey man! this looking good 🚀 @beastoin 

Could you start creating a draft PR of this?

Thanks

**Comment by beastoin** [comment]
yes @josancamon19 , the PR & feature demo will be dropped today. (gmt+7)

**Comment by beastoin** [comment]
### Thinhs change logs
1. PR & Feature Demo have been dropped @ https://github.com/BasedHardware/Omi/pull/593 , waiting for feedback & code review 🏄‍♀️
2. What's next?
  - ✅ Draft the proposal
  - ✅ Waiting for feedback / assigns
  - ☑️ Implement (make it happen) (70%)
    - ✅ Create Zapier App for Friend
    - ✅ Create Trigger Friend’s memory created on Friend Zapier
    - ✅ Create Action Save memory to Friend
    - ☑️ Publish Zapier App
      - ☑️ Feature feedback
      - ☑️ Code review
      - ☑️ Deploy @ Submit to Zapier

Good day!

**Comment by beastoin** [comment]
> Hey man! this looking good 🚀 @beastoin
> 
> Could you start creating a draft PR of this?
> 
> Thanks

hi @josancamon19 please find the PR / Feature Demo at https://github.com/BasedHardware/Omi/pull/593/ 

Cheer!

**Comment by josancamon19** [comment]
Finished by @beastoin taking to production today.
