### ISSUE TITLE
Plugin for users to be able create Make.com integrations when a memory created. ($1500) 

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#536]
**Is your feature request related to a problem? Please describe.**
Users want to be able to connect Make.com with their Friend app. Users want a trigger "on memory creation" and action "create memory in Friend App"

**Describe the solution you'd like**
You need to make a "Make.com" plugin for Friend app, in which the user will be able to authorize Make.com app and connect Friend app to other apps
Along with that you need to submit the integration into make.com marketplace. You can ping me or @josancamon19 once you have the code for integration ready

You need code for 2 features:

- Trigger on memory creation (should work as a trigger in Make once new memory is created).
Example: I am wearing friend and just finished a conversation => memory got created. I want to be able to put it into my notion table through Make (so I need to have a trigger on memory creation)
- Action (Create memory) - should work as an action in Make so that users are able to create "memories" in friend app. Example: you created a new page in notion => it should automatically go to Friend's backend

[Learn how to create plugins here](https://docs.basedhardware.com/developer/plugins/Introduction/)

**Describe alternatives you've considered**
Check example: https://www.make.com/en/help/ai-in-make/mem

**Additional context**
This is a paid task. Reward is $1500 in cash. Simply link your PR with this task and we will check it asap. Check how Contributions and bounties work [here](https://basedhardware.com/contribute)
If no one is assigned to this task, then no one is working on it. We don't lock bounty tasks unless you've created PRs before.

**Comment by iamhitarth** [comment]
I'd love to work on this @kodjima33 🤚 

Built a couple of plugins previously: https://github.com/BasedHardware/Friend/pull/459

**Comment by kodjima33** [comment]
@iamhitarth locked on you, please create a new fork. If you stop working on it, will unlock

**Comment by sadeedameen** [comment]
Hi @kodjima33,

I am Sadeed, a Certified Make expert and gold partner of Make.
 
I can help you in building custom app in Make.com. You can check my apps released in make:
**DocCrafter, 0CodeUtil** (verified ones)
Other Make.com apps here: [https://www.msquare.pro/products
 ](https://www.msquare.pro/products
 )
I can deliver this in 10 hours. However, I want following details:
Endpoint in CurlScript
Authorization key for testing.

Thanks

**Comment by josancamon19** [comment]
Hey @iamhitarth 

No progress on this task, please create a DraftPR, or I will unassign.

**Comment by 0w9** [comment]
I would love to work on this.

cc @josancamon19 Switching over from Zapier.

**Comment by 0w9** [comment]
The trigger is basically ready to be tested. Need to do more debugging tho.

**Comment by 0w9** [comment]
Update: I will create the pull by tomorrow. Ended today finishing the trigger. Issues so far have been that Make.com does not offer a OAuth 2.0 integeration. Their API only is for paid tiers. So users will have to copy their UID then submit it in Make.com for setup. To make it easier I will just add a link to copy it inside the Readme.

**Comment by 0w9** [comment]
Hey. Thanks for yesterday's event. I will move the code to Modal today and create a PR. For the other feature (Make.com → Friend) I will also work on that.

**Comment by josancamon19** [comment]
Looking forward for the Draft PR @0w9

**Comment by iamhitarth** [comment]
Sorry folks had a super busy week at work but looks like @0w9 is on it 👍 

Lemme know if I can help 🙏

**Comment by josancamon19** [comment]
Update, not planned for now.
