### ISSUE TITLE
Opt-in consent

### ISSUE THREAD

**Issue by MichaelReaNZ** [BasedHardware/Omi#550]
I believe ethically we should have at least the ability for a consent mechanism (this might not technically easy at this point but I think we should be thinking about a mechanism).

We would have to identify known speakers.
Have them state their consent and optimal timeout for that consent.

In some countries there may be legal issues with recording I think giving the user the option to use this is a good move.

I've got eyes on Speechmatics flow it like a great technology for recognition and diarization.

**Comment by iamthegone** [comment]
Diarization is so hit or miss I don't believe this is feasible right now. I was having a conversation with myself and it thought 4 speaker were talking. I've looking into diarization extensively for meeting minutes as well and nothing works even close to what you could call 'reliably'.

Legal issues will be tough here and I think each user will have to make their own call - likely lots of us operating illegally for the foreseeable future. Not sure if a 'hands up' emoji is appropriate but that's where I believe we are today.

**Comment by josancamon19** [comment]
Yea, unfortunately as mentioned, this is not feasible yet, tech simply is not there yet, hopefully once that's the point, we'll do it.
