### ISSUE TITLE
Circuit Diagram for Friend Dev Kit V2

### ISSUE THREAD

**Issue by Neotastisch** [BasedHardware/Omi#555]
**Is your feature request related to a problem? Please describe.**
It is quite hard to understand which ports need to be connected from a single picture and with no documentation

**Describe the solution you'd like**
A simple diagram for connecting the different parts. Even better would be a guide for inexperienced users

**Additional context**
PS: If I get a diagram I would be happy to make a guide for assembling it

**Comment by neooriginal** [comment]
@kodjima33 
Will there be a switch to turn it on and off? There are none listed in the parts list. Is that a mistake?

**Comment by josancamon19** [comment]
@ro-kirchev

**Comment by josancamon19** [comment]
@gashpid
