### ISSUE TITLE
Add support for external microphone 

### ISSUE THREAD

**Issue by Neotastisch** [BasedHardware/Omi#562]
**Is your feature request related to a problem? Please describe.**
Please make it so we can connect microphones to the board. This is also necessary for future generations, if an external microphone is added

**Describe the solution you'd like**
Automatically detects microphone if connected to a specific gpio

Would be great for public meetings when the build in microphone is too weak

**Comment by josancamon19** [comment]
Hi, this is something not planned for now nor the near future.
