### ISSUE TITLE
[Friend V2] Action button firmware characteristic ($500)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#566]
**Is your feature request related to a problem? Please describe.**
Friend App should have a firmware characteristic that notifies when the button is pressed.

**Describe the solution you'd like**
There should be a firmware characteristic in the firmware that listens for the button click.

The app should read the characteristic and trigger whatever you want for now (based on that)

**Comment by midepeter** [comment]
Hello @josancamon19, 

I assume this is a paid task. I will love to take on this and make a PR soon😊

**Comment by josancamon19** [comment]
@kevvz please comment here so I can assign this to you.

**Comment by kevvz** [comment]
hello
