### ISSUE TITLE
[Friend V2] Friend can speak ($700)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#567]
**Is your feature request related to a problem? Please describe.**
I want to be able to use the speaker of my Friend Programatically.

**Describe the solution you'd like**
A speaker characteristic should be made, which you can write bytes to it, and play an audio.

Test it by taking the plugin response text, then using 11Labs or deepgram tts, to play that on the device.

**Comment by abls** [comment]
Working on this @ hackathon rn

**Comment by josancamon19** [comment]
No progress, unassigning.

**Comment by kevvz** [comment]
https://github.com/user-attachments/assets/3aa1b4ad-e9d6-45f0-a729-d743854bcac5

Im gonna wait until the accelerometer PR is done since my main branch has that code on accident and I can't seem to move anything without destroying that branch

The button PR also works
