### ISSUE TITLE
[Friend V2] Friend uses NFC for pairing ($500)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#568]
**Is your feature request related to a problem? Please describe.**
I want to be able to pair my Friend by using NFC instead of bluetooth discovery.

**Describe the solution you'd like**
- A characteristic that sets the NFC value to the device id.
- An update to the connection page to connect by using NFC instead of scanning for devices.

Connection, reconnection logic should remain the same, but the devices list should simply include the id of the device you NFC to.

**Comment by Jainakin** [comment]
I want to take this task, need a little more information, do I also need to add NFC connection functionality to the Friend Firmware or just on Flutter App.
Thanks!

**Comment by kevvz** [comment]
Is there a particular NFC antenna we should use?

**Comment by hlord2000** [comment]
Not working on this but iOS does not support NFC (OOB) pairing last I saw

**Comment by vincentkoc** [comment]
Submitted initial PR #610 

We can make iOS and Android pairing work using App Links which will pickup on the URL link and pull into app and start pairing, otherwise you end up on website with a lost and found style message and setup instructions. This is how most airtags etc work in the easy way.

**Comment by vincentkoc** [comment]
We are missing antennas on devices so this is also something that needs to be resolved, but will not need code/pin/overlay change for that.

**Comment by josancamon19** [comment]
NFC feature (firmware) completed. https://github.com/BasedHardware/omi/pull/610.

App side will be developed later.
