### ISSUE TITLE
[Friend V2] Friend can use accelerometer and gyroscope. ($500)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#569]
**Is your feature request related to a problem? Please describe.**
I want to be able to retrieve gyroscope and accelerometer data from my Friend device.

**Describe the solution you'd like**
Test this feature by receiving the data with accelerometer and gyroscope, and make a fake the detect if your Friend falls, that triggers a notification that says smth about it.

**Comment by kevvz** [comment]
Please see my full code, I added firmware to be able to expose the accelerometer, it's not just one dot I swear! Wasn't too familiar with PRs lol

**Comment by josancamon19** [comment]
Will review soon, thanks for the PR

**Comment by francip** [comment]
I'd suggest we support this for DevKit 1 as well.

**Comment by kevvz** [comment]
I think it does! Both versions have the same accelerometer, so in theory any firmware that uses the accelerometer will work on both.

**Comment by francip** [comment]
Yes. This was more of a comment so that the app doesn't try to gate this based on the hardware revision. :-)
