### ISSUE TITLE
[Friend V2] Onboard Memory Part 1 ($1500)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#570]
**Is your feature request related to a problem? Please describe.**
I want my Friend to be able to store my recordings even when the device is disconnected.

**Describe the solution you'd like**
- Create a characteristic that stores the audio files to the sd card while the device is disconnected.
- Create another characteristic that lists all the audio files available in the sd card + their size and estimated length.
- Create another characteristic that starts streaming those audio files 1 by 1.

This ticket should be mainly on the firmware side, but ideally you create in capture/page.dart a button to view the list of of offline recording files available + an option to start receiving them and print them in the console.

**Comment by kevvz** [comment]
Is there already code that allows us to interact with the sd card or do we have to write it ourselves?

**Comment by vincentkoc** [comment]
I will like to take this one today to start working on storage as discussed :)

**Comment by vincentkoc** [comment]
@josancamon19 can you review #590 , i will be splitting the PRs

**Comment by josancamon19** [comment]
Done by @kevvz
