### ISSUE TITLE
Remove capture page, and from the moment one start speaking, a memory in progress should appear.

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#606]
**Is your feature request related to a problem? Please describe.**
- I want to make sure memories are not lost
- A better onboarding experience, when having your first memory automatically created.
- UI simplification, removing one whole tab, and having memories as main.

**Describe the solution you'd like**
This requires the backend to determine when a memory is created.
- How to determine new memory id.
- So the websocket once it receives transcript, it should schedule a 2 minutes event that finishes the conversation.
- Once the conversation is finished, the memory object should be sent back in the websocket to the app.
- The mobile UI should handle this by having in progress memories + removing capture/page.dart.
- Websocket reconnection has to handle "memory in progress" scenarios.

**Comment by josancamon19** [comment]
The idea here @beastoin is to modify the websocket behavior a little bit.

1. The backend should have the 2 minutes timer determining when to create a memory, not the app.
2. The app would handle receive events from the websocket and act accordingly, this will be either new segments of a memory, a new memory was created, etc.
3. Post processing should be handled on the backend side, this means we should be able to keep a temporal version of the file while a memory is in progress.
4. capture/page.dart should be removed, instead we should have only memories page, and when a new memory starts, it should appear there, on top as in-progress. -> on memory detail opened, it should show summary in progress, but show the current transcript as it goes.

**Comment by beastoin** [comment]
interesting! lemme 🏄‍♀️

**Comment by josancamon19** [comment]
More context.

![Image](https://github.com/user-attachments/assets/ba9e6766-a826-42d6-bc74-595ed3cf3d4f)

**Comment by beastoin** [comment]
PR: https://github.com/BasedHardware/Omi/pull/684
