### ISSUE TITLE
Docs Improvement ($100/month)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#614]
Our [Docs](https://docs.basedhardware.com) require recurrent updates. 

Every month, the most active docs contributor will receive $100 in cash.

How we measure: # of lines committed to docs folder. 

if you made the largest amount of contributions to docs this month, please email team@basedhardware.com (every 1st day of new month) with a list of your commitments and Paypal address.

**Comment by preeti13456** [comment]
Does the docs has been shifted to somewhere else actually I was trying to refer them as to run on my local which got rebooted recently 

PS: Trying to contribute

**Comment by josancamon19** [comment]
Found that person already, @smian1
