### ISSUE TITLE
Migrate to Provider (for State Management)

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/Omi#631]
This work is being tracked on the `provider-migration` branch.

- [ ] Device state
- [ ] Websocket
- [ ] Memories
- [ ] Messages
- [ ] Capturing
- [ ] Settings

**Comment by mdmohsin7** [comment]
Unable to assign @Becca-Saka for some reason. But she is also working on it

<img width="414" alt="Screenshot 2024-08-22 at 10 18 44 AM" src="https://github.com/user-attachments/assets/d7e3b15e-7f83-4882-a15a-32c9598b9227">

cc: @josancamon19

**Comment by josancamon19** [comment]
Closed by @mdmohsin7
