### ISSUE TITLE
Create bluetooth characteristic using circuit-python ($1000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#638]
**Is your feature request related to a problem? Please describe.**
Current firmware for Friend Dev kit 1 is written in C. There are not many developers for C. We want to try circuit-python

**Describe the solution you'd like**
You need to do only 1 thing: create Bluetooth characteristic for the XIAO nrf52840 sense board (our current board for Friend dev kit 1) 

How this will be tested: create firmware and attach uf2 file. We will flash the firmware and will try to connect via Bluetooth characteristic reader like Bluesee

**Additional context**
This is a paid task. Reward is $1000 in cash. Simply link your PR with this task and we will check it asap. Check how Contributions and bounties work [here](https://basedhardware.com/contribute)
If no one is assigned to this task, then no one is working on it. We don't lock bounty tasks unless you've created PRs before.

**Comment by abhishek818** [comment]
@kodjima33  Can i pick this up?

**Comment by josancamon19** [comment]
Is this micropython, or circuit python?

**Comment by kodjima33** [comment]
> @kodjima33 Can i pick this up?

@abhishek818 you definitely can. I can't lock this on you before your first PR (I assume you didn't yet do any PRs) - but once you do any PR, I can lock

**Comment by siddhartpai** [comment]
I have started work around this

PR :  #650

**Comment by siddhartpai** [comment]
@kodjima33 Can you give a bit more context on bluetooth characteristic? 

Is it enough to get the data for gyro through a uart subscription, encoded as a hex? 

Or maybe i haven't understood the full scope of the task here.

**Comment by josancamon19** [comment]
Create a bluetooth characteristic that streams the audio bytes via bluetooth, using opus codec.

**Comment by josancamon19** [comment]
@siddhartpai

**Comment by siddhartpai** [comment]
@josancamon19 I was looking at this, and seems like there are currently no opus libs currently for CircuitPython. There's been some work done around modifying micropython opus libs to circuitpython; however it is not very promising( https://github.com/orgs/micropython/discussions/10756 ).

Let me know any if you have any thoughts or direction around this.

**Comment by josancamon19** [comment]
Shit, thanks, then this is not viable
