### ISSUE TITLE
Firmware V1.0.4 blue light bug: if device is disconnected, the light is still blue (should be red) ($300) 

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#649]
**Describe the bug**
Now: if device is disconnected from the app, the light is still blue (should be red)

**To Reproduce**
1. Connect the necklace to Friend app
2. Disable Bluetooth or kill the process or try other ways of killing the connection (if in all of these still works, just wait 1-2 hours)
3. You'll see that device is still blue (and it should be red)

**Expected behavior**
Should be red light if device is disconnected

**Desktop (please complete the following information):**
 - OS: IOS
 - Version: 1.0.28 (testflight)

**Smartphone (please complete the following information):**
 - Device: Iphone 13

**Additional context**

This is a paid task. Reward is $300 in cash. Simply link your PR with this task and we will check it asap. Check how Contributions and bounties work [here](https://basedhardware.com/contribute)
If no one is assigned to this task, then no one is working on it. We don't lock bounty tasks unless you've created PRs before.

**Comment by mdmohsin7** [comment]
More context:
I connected the device, and then disconnected it and unpaired it. The light did change to red. But then I went to connect the device again, this time the device did not show up in the list and the light changed from red to blue.

https://github.com/user-attachments/assets/1e69770a-99da-4f65-8fc9-2f788020bca6

**Comment by beastoin** [comment]
man @mdmohsin7 please help me on testing this case with the latest app ver :)

**Comment by josancamon19** [comment]
was not a firmware issue.
