### ISSUE TITLE
Cannot charge device 

### ISSUE THREAD

**Issue by paulsybrandy** [BasedHardware/omi#655]
I have the Dev friend device and three times now I have plugged in the device  via usb-c and let it sit thinking it was charging and now it is completely dead with no power. Possibly a deffective device?

**Comment by josancamon19** [comment]
Have it turned on (Switch on) while charging please, and let us know.

**Comment by josancamon19** [comment]
This is probably not an issue to include here, please reach out on discord, to check, what might have happened. Thanks.
