### ISSUE TITLE
Create metric to measure how many people have enabled notiications and ask for notifications better

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#659]
Depends on #395

**Comment by josancamon19** [comment]
https://github.com/BasedHardware/Omi/issues/395 depends on

**Comment by josancamon19** [comment]
Create an A/B test using growthbook, to determine how many people enable or not, if we enforce more or less, people leaving etc.

**Comment by mdmohsin7** [comment]
Notification Mixpanel pending

Edit: Now on main
