### ISSUE TITLE
android app cannot connect to Omi (friend) (only shows loading animation infinitely)

### ISSUE THREAD

**Issue by SaschaHeyer** [BasedHardware/omi#663]
**Describe the bug**
Friend is found with the Android App (see screenshot) but only shows a loading animation. Nothing else happens. 

**To Reproduce**
1. Go to and install the firmware https://docs.basedhardware.com/assembly/Install_firmware/ I installed this version https://github.com/BasedHardware/Omi/tree/main/Friend/firmware/firmware_v1.0 following the exact instructions like here https://docs.basedhardware.com/assembly/Install_firmware/
2. upload the file zephyr.uf2 to the xiao nrf
3. disconnect USB connect USB again
4. Open android app (device is found)
5. click on device and than only a loading animation is shown

**Expected behavior**
able to connect to the device

**Screenshots**
![Screenshot_20240825-155537](https://github.com/user-attachments/assets/49c54399-64b5-4618-9ae4-11f15f9a756b)

**Desktop (please complete the following information):**
 - OS: Android
**Smartphone (please complete the following information):**
 - Device: Pixel 6

**Comment by josancamon19** [comment]
Did you upload both bootloader and firmware?

Also, if you kill and reopen the app, this still happens?

**Comment by mdmohsin7** [comment]
Does this happen with the latest version @SaschaHeyer?

https://github.com/BasedHardware/Omi/releases/tag/v1.0.29%2B97-android-dev

**Comment by josancamon19** [comment]
Reopen if the issue persist @SaschaHeyer
