### ISSUE TITLE
Replace Expensive Pinecone with Milvus

### ISSUE THREAD

**Issue by tspannhw** [BasedHardware/Omi#703]
**Is your feature request related to a problem? Please describe.**
Pinecone causes problems with accounts, tokens and pricing.

**Describe the solution you'd like**
Milvus is and Apache licensed, industry leading vector database that is open source, runs in either Milvus-Lite in just Python/Jupyter, Docker, Docker Compose, Standalone, Distributed or in Zilliz Cloud.   Milvus is https://lfaidata.foundation/projects/milvus/

**Describe alternatives you've considered**
Similiar apis, better performance and can run anywhere.   Including on VM, Containers, Docker, Raspberry Pi and NVIDIA Jetson.

**Additional context**
I can assist, I am the Developer Advocate for Milvus and also owner of the dev kit.   https://medium.com/@tspann

**Comment by josancamon19** [comment]
Hi, pinecone works for now, and most people would never get charged on free tier, and for us is like 1 usd per month, maybe will be considered later, thanks.
