### ISSUE TITLE
Private server easy setup

### ISSUE THREAD

**Issue by eladrave** [BasedHardware/omi#735]
The goal is to allow easy setup of a "private" server.
The best way to do it, IMHO it should be an easy setup, followed by logging in to a management portal, where the admin needs to set up the mandatory thing:
API keys etc...
DB

And then to create "users", assign a key to each one, so they can configure it on their phone app

Not sure how I can bounty this, but I'll put $500 for it

**Comment by IsitorViper** [comment]
Hi, I would like to work on this

**Comment by eladrave** [comment]
@IsitorViper By all means! Not sure if you need my permission or something :)

**Comment by eladrave** [comment]
@josancamon19 
Why can't we keep this open? I mean, if someone wants to do it, and it's an open source community, we should be able to, shouldn't we?
