### ISSUE TITLE
Migrate to Intercom setup

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#753]
- [x] Replace use intercom instead of Gleap
- [x] Improve the UI, te right sided toggle, looks bad, and bothers some users.
- [x] Set user properties the same way Mixpanel is doing
- [ ] Include events simply adding to Mixpanel event logger.
- [x] Enable push notifications.
- [ ] Setup logs, tags, and network logs.
- [x] Make sure Gleap is clean of users requests.
- [x] Setup Intercom bot so it can answer users requests automatically
- [x] Setup Intercom FAQ so users know stuff that is going on

**Comment by josancamon19** [comment]
Can sync github issues with Roadmap?

**Comment by josancamon19** [comment]
Quick test if provide great UI
Interom tasks completion 
- Setup your speech profile
- Create your first memory
etc...

Just a quick test to see if worth it and improves user experience.

**Comment by mdmohsin7** [comment]
> Set user properties the same way Mixpanel is doing

using custom data attributes
https://www.intercom.com/help/en/articles/320-tracking-user-data-in-intercom

> Include events simply adding to Mixpanel event logger.

![Image](https://github.com/user-attachments/assets/bcd493a6-74b8-46bb-97d6-5ae57be948b3)
Should all types of events be included? That are already being logged through mixpanel?

> Setup logs, tags, and network logs.

Should we use the same event logger of intercom for this stuff as well? Because I can't seem to find anything else related to this on Intercom

**Comment by mdmohsin7** [comment]
> Quick test if provide great UI Interom tasks completion
> 
> * Setup your speech profile
> * Create your first memory
>   etc...
> 
> Just a quick test to see if worth it and improves user experience.

I'm not sure if I fully understand this. Could you please clarify?

**Comment by josancamon19** [comment]
That was just a thought, I know intercom has some "Get started" task, like gamiification
Similar to discord initial tasks when you enter a channel, just to explore, like a few extra onboarding exprience.

**Comment by josancamon19** [comment]
> > Set user properties the same way Mixpanel is doing
> 
> using custom data attributes https://www.intercom.com/help/en/articles/320-tracking-user-data-in-intercom
> 
> > Include events simply adding to Mixpanel event logger.
> 
> ![Image](https://github.com/user-attachments/assets/bcd493a6-74b8-46bb-97d6-5ae57be948b3) Should all types of events be included? That are already being logged through mixpanel?
> 
> > Setup logs, tags, and network logs.
> 
> Should we use the same event logger of intercom for this stuff as well? Because I can't seem to find anything else related to this on Intercom

Can we sync intercom with mixpanel somewhere else? I would prefer not to spend that network data, surely there exists a Mixpanel <> intercom integration, if not just put the line to log all events in 

```
void track(String eventName, {Map<String, dynamic>? properties}) =>
      _mixpanel?.track(eventName, properties: properties);
```

But let's not use it for now, it would be great to have access to their mixpanel profile URL from intercom.

**Comment by josancamon19** [comment]
Ignoring remaining todo's keeping Instabug.
