### ISSUE TITLE
Battery drain issue on the Omi Android App [w36]

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#785]
**Context:**

![Image](https://github.com/user-attachments/assets/01267b25-6f7b-4d37-87d4-492f80a2c7c2)

my android battery is drain badly. no connection to internet, no device found. 

context: i put my phone to the pocket, then have went out from 30m ago. keep Omi app open, no internet or device(friend)
the question is: why mic still on!

*top right, green icon, mic

i guess that the app still use mic

try turnoff the mic permission for Omi, let see what happen 

yes, no heating anymore.

so i guess we found 1 case causing battery drain on android ver.

**Objective:**
- [ ] No-more battery drain on android app

**Key results:**
- [ ] Phone mic should be turned off when not in used

**Comment by beastoin** [comment]
week # 36
