### ISSUE TITLE
Can no longer export summaries (last upgrade)

### ISSUE THREAD

**Issue by paulsybrandy** [BasedHardware/omi#791]
![github-issue-submission](https://github.com/user-attachments/assets/cde489b0-3045-4994-ac2c-1ef2fdf79876)

**Describe the bug**
After the last upgrade (which I did ten minutes ago) the Export Summary option is no longer available.

**To Reproduce**
1. Start Omi Android app.
2. Let app connect to device.
3. Go to Memory I want to export summary of.
4. Tap the menu icon.
5. No longer have an option to export summary. There is an option to share but the link it sends is not a valid link either.

**Expected behavior**
When clicking the menu button within the memory I expected to see the normal options of export to PDF or TXT.

**Screenshots**

![Screenshot_20240908-010748_Friend](https://github.com/user-attachments/assets/b1f923f3-93a8-47f6-8365-be6e82254ff8)

**Desktop (please complete the following information):**
 - OS: Windows 11 version 23H2 (OS Build: 22635.4000)

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus 5G (2024)
 - OS: Android 14
 - Browser Microsoft Edge Dev
 - Version 130.0.2807.0

**Additional context**
I was exporting all day yesterday without an issue. Right after I upgraded a short time ago the option no longer appears.

**Comment by mdmohsin7** [comment]
Hi @paulsybrandy, exporting of summary and transcript has been moved to the `share` section on the screen

![Image](https://github.com/user-attachments/assets/127186dc-8522-42e3-a371-cca8b507ed00)

**Comment by paulsybrandy** [comment]
There used to be an `Export to PDF` option for PDF... is `Send Summary` the same thing, exporting to PDF?

**Comment by josancamon19** [comment]
Hi @paulsybrandy why is it important for you to export as PDF? I would love understanding what's not good about current export options, thanks

**Comment by paulsybrandy** [comment]
Exporting to PDF is much cleaner with headings being larger and overall professional look. Just exporting text doesn't display any formatting whatsoever and it is harder to find things when needed.

**Comment by paulsybrandy** [comment]
Exporting to PDF is much cleaner with headings being larger and overall professional look. Just exporting text doesn't display any formatting whatsoever and it is harder to find things when needed.
