### ISSUE TITLE
Improve bt_device object to include more details about the device

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#792]
Including bt_device object to have firmware version, and firmware details as part of the object, instead of separate preferences, ideally includes bootloader, fwver, etc.

<img width="959" alt="Screenshot 2024-09-08 at 11 16 19 AM" src="https://github.com/user-attachments/assets/662e4179-3819-4323-be83-973d37b2eb06">

**Comment by mdmohsin7** [comment]
<img width="281" alt="Screenshot 2024-09-18 at 7 47 59 PM" src="https://github.com/user-attachments/assets/690355a8-5fb9-464e-8b82-eacd15fa54d1">

Should we change the device type from `friend` to `devKit1`?

**Comment by mdmohsin7** [comment]
There are two different objects basically holding the same information to an extent. And both of them are dependent on each other (`DeviceInfo` and `BTDeviceStruct`)
```
class DeviceInfo {
  String modelNumber;
  String firmwareRevision;
  String hardwareRevision;
  String manufacturerName;
  DeviceType type;
  }
  ```
  ```
  class BTDeviceStruct {
  String name;
  String id;
  int? rssi;
  List<int>? fwver;
  DeviceType? type;
}
  ```
The DeviceInfo object has methods to read characteristics to get data like the firmware version, hardware name etc., But it depends on BtDeviceStruct to differentiate between device type using the `type` property. And in many places in the code, both of them are being used together.

Both of them can be combined together to have a unified object for device details.
 ```
  class BtDevice {
    String name;
    String id;
    int? rssi;
    DeviceType type;
    BtDeviceInfo? btDeviceInfo;
   }

class BtDeviceInfo {
  String modelNumber;
  String firmwareRevision;
  String hardwareRevision;
  String manufacturerName;
  }
   ```
   
 The `BtDevice` will also includes methods to convert `BluetoothDevice` (from flutter_blue_plus) to `BtDevice` etc., apart from the already existing methods, getters and setters. The `BtDeviceInfo` is basically `DeviceInfo` but renamed to `DeviceInfo`

**Comment by josancamon19** [comment]
That makes sense

**Comment by mdmohsin7** [comment]
Closing it as it has been clubbed with #828
