### ISSUE TITLE
Summarization language

### ISSUE THREAD

**Issue by Blueforcer** [BasedHardware/omi#823]
**Is your feature request related to a problem? Please describe.**
While I can set the speech recognition to German, the summary and "Abouts" are still written in English. 

**Describe the solution you'd like**
LLM should  output in the same language as the input language

**Describe alternatives you've considered**
It should be possible to realize this with a extended prompt. like
"Write in [selected language]"..

**Comment by azdolinski** [comment]
+1
It is doing Polish transcript.. but summary is in English.

**Comment by josancamon19** [comment]
Hi, thanks for posting, but this is not planned for now.

**Comment by Blueforcer** [comment]
Can you explain this decision?
Changing "Use English for your response." to "Use {language_code} for your response". should do the trick. Maybe just optional?
https://github.com/BasedHardware/omi/blob/1b4fd1edda12564c1c1903480df2a90e87a687af/backend/utils/llm.py#L78

**Comment by azdolinski** [comment]
I agree with @Blueforcer. By closing this, you are showing _ignorance_ to the rest of the “non-English speaking” world and drastically limiting the scope of the product to people who only use English - where this change can easily be made by adding an additional **{language_response}** parameter injected into the get_transcript_structure prompt and allowing the same settings/variable to be used in plugin prompts.

@kodjima33 - can you share your opinion?
On behalf of other countries that use ie. PL, DE, ES, ZH, HI

**Comment by wHyEt** [comment]
@josancamon19 I don't get why this is closed this is a highly needed feature since this product is used all over the world
