### ISSUE TITLE
docs aren't published

### ISSUE THREAD

**Issue by legut2** [BasedHardware/omi#835]
**Describe the bug**
https://docs.basedhardware.com/ is down and doesn't get published. 

**To Reproduce**
1. Go to https://docs.basedhardware.com/

**Expected behavior**
Page loads and can view docs.

**Screenshots**
![Screenshot 2024-09-13 102317](https://github.com/user-attachments/assets/e62e573e-5b42-49a8-b72e-acaa5000d013)

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**
 - Device: iOS

**Comment by josancamon19** [comment]
Fixed already, pls check docs.omi.me

**Comment by legut2** [comment]
Oh, it moved. I didn't realize that. It might be worth redirecting docs.basedhardware.com to docs.omi.me.
