### ISSUE TITLE
Migrate new BLE connectivity management with Frame Device

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#864]
**Action**
- [ ] Download the latest version from Testflight / Internal Test, and test on Frame Device

**Comment by josancamon19** [comment]
Test it doesn't work : /

Renaming this, to migrate Frame integration to new architecture of connectivity, let's not worry about it much for now.

**Comment by beastoin** [comment]
holyyy...

**Comment by josancamon19** [comment]
We can dismiss this for the future, not on close roadmap
