### ISSUE TITLE
Memory processing cases that result in a bad User experience

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#868]
**Edge cases to be handled:**

- [x] When I have a conversation in progress, if I disconnect the device or the battery's off, or similar, the current conversation disappears, Instead it should maintain there and say "Waiting for reconnect...". Probably `_getMemoryHeader`
- [x] If I have a memory in progress, and kill, open the app before the memory starts processing, I expect the conversation to still be there, so the websocket should sync and show the previous content in the "in progress". (I see after processing prev transcript + new transcript works, it's just to show that properly on the user side while in progress)
- [x] Once the backend starts processing the memory ("120 seconds mark"), that transcript should be moved below in the capture item, to another list item, that says "Processing" and has a circular progress indicator instead of an emoji. Once completed processing, it should highlight, a small animation + maybe a snackbar (but only trigger once, save a preference for it). New segments after "processing" started, should be in the capture item.
- [x] When a memory is processed, and becomes discarded, but showDiscarded is not true, we should still show them, until the app is restarted, as a user, I have a few conversations and go back to the app, and don't see anything, I right away think it failed, until I remember it might have been discarded.

**Solution**
- Processing memory with new field: status(capturing, processing, done), capturing_to
- Capture provider track `capturing_to`, `capturing` status of processing memory
- New session at Memories page for processing memories, track `processing` status, bellow capturing item. Use poling for now, send new memory forcing showing to the memories session.

**Comment by beastoin** [comment]
Let's go!

**Comment by beastoin** [comment]
**Solution**
- Processing memory with new field: status(capturing, processing, done), capturing_to
- Capture provider track `capturing_to`, `capturing` status of processing memory
- New session at Memories page for processing memories, track `processing` status, bellow capturing item. Use poling for now, send new memory forcing showing to the memories session.

**Comment by josancamon19** [comment]
Testing

**Comment by josancamon19** [comment]
![Image](https://github.com/user-attachments/assets/c5a8faee-89bf-434b-a7bd-462230965ed4)


Duplicate isue

**Comment by beastoin** [comment]
yup

**Comment by beastoin** [comment]
also this, any UX enhancement needed? bro @josancamon19
