### ISSUE TITLE
IOS: Cannot delete memory

### ISSUE THREAD

**Issue by thestumonkey** [BasedHardware/omi#873]
**Describe the bug**
Cannot delete memory on IOS

**To Reproduce**
1. Create a memory
2. click on memory
3. select ... and delete
4. Taken back to memory list with memory still present.  refreshing screen does nothing, and you can click on the memory again

**Expected behavior**
- Toast messages shown "memory deleted"
- Return to memory list in same position as before (in case user wants to delete multiple memories in a large list
- Memory is not present

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Version 1.035+125

**Smartphone (please complete the following information):**
 - Device: iphone 15
 - OS: 17.6.1

**Additional context**

https://github.com/user-attachments/assets/5527cfb0-e260-48d6-9986-c3cc505a3b6b

**Comment by mdmohsin7** [comment]
Hi there, the issue has been resolved in the latest version, which is currently under review by Apple. It will be available once the review is complete. Thank you for reporting it!
