### ISSUE TITLE
Explain when a memory get's created, nobody seems to know 2 minutes, or device disconnection

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#888]
- [x] Summary tab of memory detail while a memory is in progress, should include 
   - [x] A button that let's me cut the memory until that point, and let's me summarize whatever is in there (this should never be discarded).
   - [x] an explanation, that conversations get processed when there's no more transcript detected for 2 minutes. This has to look good, and be clear, easy to catch up for people.

Ratio of success of this implementation is how many people keep asking about when memories get created in discord but also on other support channels.
- [x] Include a 1 week after implementation reminder to check if it was successfully and let us know.

**Comment by mdmohsin7** [comment]
Checked Intercom for tickets of the last 2 weeks, and there has been only 2-3 tickets asking how to charge the device. And the article has received 119 views so far

![Image](https://github.com/user-attachments/assets/f5a73407-ca04-4088-b2da-aaf19c0afaed)

**Comment by josancamon19** [comment]
nice

**Comment by josancamon19** [comment]
Still, the seconds counter doesn't work.
And the message could be prettier, and slightly bigger, more centered.

**Comment by mdmohsin7** [comment]
> Still, the seconds counter doesn't work

It picks up duration from the last segment. Let me know if I should change it and have an actual timer

**Comment by beastoin** [comment]
ding dong @mdmohsin7

**Comment by mdmohsin7** [comment]
> ding dong @mdmohsin7

This as well is done! XD
