### ISSUE TITLE
Omi app no longer connecting to Omi Devkit 1

### ISSUE THREAD

**Issue by smokelore** [BasedHardware/omi#944]
I loved this device when it was working! Would love to get it functional again. Thanks in advance for any help.

**Describe the bug**
Around the time that Friend became Omi, the app stopped proceeding past the first screen (a splash screen with the Omi logo in the center). I speculate that this is because it expects to connect to Omi Devkit 1 but never finds it. 

In an attempt to fix this, I have updated the firmware on the Omi Devkit 1 to `bootloader0.9.0.uf2` and `firmware1.0.4.uf2`, but the app still hangs at the splash screen and I am unable to use my Omi device. 

I have also tried clearing the cache of the Omi Android app and reinstalling it but that has not resolved the issue.

Attempting to connect to the Omi device manually via the Android Bluetooth "Pair new Device" settings  results in the error dialogue "Pairing rejected by Friend".

**To Reproduce**
1. Turn on Omi device (the light remains static red)
2. Open Android app
3. App hangs on splash screen and never connects to Omi device

**Expected behavior**
Android app should either connect to Omi device automatically, or begin the device setup user flow.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Android 14

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14

**Additional context**
Is there a way to reset the device/app to force the device setup user flow to occur? At this point I would expect the Omi Devkit 1 device to blink blue and search for a Bluetooth connection.

**Comment by mdmohsin7** [comment]
Could you please confirm the version of the app you're currently using? Also, was this a fresh installation from the Play Store?

> In an attempt to fix this, I have updated the firmware on the Omi Devkit 1 to bootloader0.9.0.uf2 and firmware1.0.4.uf2, but the app still hangs at the splash screen and I am unable to use my Omi device.

Did you directly flash `0.9.0` and then `1.0.4`? The correct order is to flash `0.0.9`, and then `1.0.3`, and finally `1.0.4`

**Comment by smokelore** [comment]
@mdmohsin7 I did indeed flash directly `0.9.0` and then `1.0.4`. I had no idea I needed to flash `1.0.3` before `1.0.4`. I would gladly give that a shot now, but I can't seem to find the `1.0.3` firmware in the repo. Do you mind directing me to where I can find it? It's not in the [firmware directory](https://github.com/BasedHardware/omi/tree/main/Friend/firmware) as I expected.

**Comment by mdmohsin7** [comment]
@smokelore here you go

https://github.com/BasedHardware/omi/releases/tag/v1.0.3-firmware

https://github.com/BasedHardware/omi/releases/tag/v1.0.4-firmware

**Comment by josancamon19** [comment]
Pls reach for support on discord, is more likely a hardware issue, as the app can connect seamleslly rn.
