### ISSUE TITLE
Geolocation architecture is not optimal

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#946]
Instead of doing
```
  Future<void> _updateProcessingMemory() async {
    if (processingMemoryId == null) {
      return;
    }

    debugPrint("update processing memory");
    // Update info likes geolocation
    UpdateProcessingMemoryResponse? result = await updateProcessingMemoryServer(
      id: processingMemoryId!,
      geolocation: geolocation,
      emotionalFeedback: GrowthbookUtil().isOmiFeedbackEnabled(),
    );
    if (result?.result == null) {
      debugPrint("Can not update processing memory, result null");
    }
  }

```

For geolocation, we should send it to the server, not every 30 seconds, but every 5 to 10 minutes (The less the better), handling geolocation as a single entity, and then during memory processing, we should retrieve the geolocation that matches the creation timestamp.
As for omi emotional feedback, is not needed for now (disabled), but once is used again, also keep it as a backend entity.

Default geolocation to ipapi.co/json

**Comment by beastoin** [comment]
gotcha!
