### ISSUE TITLE
Remaining piece to make the most out of V1

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/omi#958]
Even if bytes get streamed, there might be connection issues, which anyways would cause data lost.

This happens a lot in events (SF), and rural areas.

This will not be solved with V2 as is.

So, 

- [ ] Internet connection tracking is reliable AF, we must be able to detect ms changes in connectivity state, also to detect when ws is not sending bytes properly.
- [ ] When no connection, or issues streaming, we should store a queue of bytes in the phone storage.

**How to sync those bytes?**
2 Options:
1. The phone detects connection, and uploads those bytes automatically
2. User manually syncs? doesn't sound sexy.

**TBD**

**What do to with those bytes?**
- Isolated memories?
- Merge with others?

Also, how to show this to the user, so experience is seamless, no idea either yet.

**Comment by beastoin** [comment]
![Image](https://github.com/user-attachments/assets/19c6be6c-5a43-4c28-b3b7-918c2830452c)

**Comment by josancamon19** [comment]
![CleanShot 2024-10-05 at 02 30 13@2x](https://github.com/user-attachments/assets/1361fe87-0f71-4a6e-ae79-12d7e004a5ad)

**Comment by beastoin** [comment]
@josancamon19 bruh, tell me more about UX enhancements ?

**Comment by beastoin** [comment]
I think we should close this ticket, feel free to lmk if there any UX improvement we could make ~
