### ISSUE TITLE
Speech Profile page improvements

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#979]
- [x] UI empty is really bad, an empty white line at the bottom.
- [x] Explain probably that language is only english, yea some people might have confused.
- [x] Page overall feels a bad initial experience.

- [x] Multiple speakers validation only happens if more than 20 words
- [x] "Try again" when multiple speakers is not triggering correctly
- [x] 150 seconds limit instead of 90, and when get to it, show a different message like "Are you still there?" instead of "Invalid speech .... " Explain that it took them too long so they will have to restart, if they did 80% of the words, let them go through.
- [x] On getting started page mention that this works only for english.

![Image](https://github.com/user-attachments/assets/24c759ba-2706-4150-a548-96d6611cb3a4)

**Comment by beastoin** [comment]
@mdmohsin7 youuuu forgot to update?

**Comment by mdmohsin7** [comment]
> @mdmohsin7 youuuu forgot to update?

Updated sir
